"""PyCSL mock for Python's tabnanny module — Tool for detecting white space related problems in Python."""
_ = 0  # anchor

#@ \trusted
#@ ensures \result >= 0
def check(file_or_dir: int) -> int:
    """Mock: If *file_or_dir* is a directory and not a symbolic link, then recursively descend the directory tree named by *file_or_d..."""
    return 0

#@ \trusted
#@ ensures \result >= 0
def process_tokens(tokens: int) -> int:
    """Mock: This function is used by :func:`check` to process tokens generated by the :mod:`tokenize` module."""
    return 0
