(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Abs.
Require int.EuclideanDivision.
Require Import ZArith Lia.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

Parameter n: Numbers.BinNums.Z.

Axiom Requires : (0%Z <= n)%Z.

Parameter i: Numbers.BinNums.Z.

Parameter c: Numbers.BinNums.Z.

Parameter b: Numbers.BinNums.Z.

Parameter a: Numbers.BinNums.Z.

Axiom LoopInvariant : ((2%Z * a)%Z = (i * (i - 1%Z)%Z)%Z).

Axiom LoopInvariant1 :
  ((6%Z * b)%Z = ((i * (i - 1%Z)%Z)%Z * ((2%Z * i)%Z - 1%Z)%Z)%Z).

Axiom LoopInvariant2 :
  ((4%Z * c)%Z = (((i * i)%Z * (i - 1%Z)%Z)%Z * (i - 1%Z)%Z)%Z).

Axiom H : (0%Z <= i)%Z.

Axiom H1 : (i <= n)%Z.

Axiom H2 : ~ (i < n)%Z.

(* Why3 goal *)
Theorem test_0215'vc :
  ((1728%Z * ((((a * b)%Z * b)%Z * b)%Z * c)%Z)%Z =
   ((((((((((((((n * n)%Z * n)%Z * n)%Z * n)%Z * n)%Z * (n - 1%Z)%Z)%Z *
           (n - 1%Z)%Z)%Z
          * (n - 1%Z)%Z)%Z
         * (n - 1%Z)%Z)%Z
        * (n - 1%Z)%Z)%Z
       * (n - 1%Z)%Z)%Z
      * ((2%Z * n)%Z - 1%Z)%Z)%Z
     * ((2%Z * n)%Z - 1%Z)%Z)%Z
    * ((2%Z * n)%Z - 1%Z)%Z)%Z).
Proof.
  pose proof LoopInvariant as Ha.
  pose proof LoopInvariant1 as Hb.
  pose proof LoopInvariant2 as Hc.
  pose proof H as Hi0. pose proof H1 as Hi1. pose proof H2 as Hi2.
  assert (i = n) by lia. subst.
  nia.
Qed.

