(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require int.Abs.
Require int.EuclideanDivision.
Require map.Map.
Require Import ZArith Lia.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

Axiom array : forall (a:Type), Type.
Parameter array_WhyType :
  forall (a:Type) {a_WT:WhyType a}, WhyType (array a).
Existing Instance array_WhyType.

Parameter elts:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z -> a.

Parameter length:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z.

Axiom array'invariant :
  forall {a:Type} {a_WT:WhyType a},
  forall (self:array a), (0%Z <= (length self))%Z.

(* Why3 assumption *)
Definition mixfix_lbrb {a:Type} {a_WT:WhyType a} (a1:array a)
    (i:Numbers.BinNums.Z) : a :=
  elts a1 i.

Parameter mixfix_lblsmnrb:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z -> a ->
  array a.

Axiom mixfix_lblsmnrb'spec'0 :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:array a) (i:Numbers.BinNums.Z) (v:a),
  ((length (mixfix_lblsmnrb a1 i v)) = (length a1)).

Axiom mixfix_lblsmnrb'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:array a) (i:Numbers.BinNums.Z) (v:a),
  ((elts (mixfix_lblsmnrb a1 i v)) = (map.Map.set (elts a1) i v)).

Parameter make:
  forall {a:Type} {a_WT:WhyType a}, Numbers.BinNums.Z -> a -> array a.

Axiom make_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (n:Numbers.BinNums.Z) (v:a), (0%Z <= n)%Z ->
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z /\ (i < n)%Z ->
   ((mixfix_lbrb (make n v) i) = v)) /\
  ((length (make n v)) = n).

Parameter i: Numbers.BinNums.Z.

Parameter k: Numbers.BinNums.Z.

Parameter parent: array Numbers.BinNums.Z.

Parameter x: Numbers.BinNums.Z.

Parameter n: Numbers.BinNums.Z.

Axiom Requires : (0%Z <= n)%Z.

Axiom Requires1 : (n <= (length parent))%Z.

Axiom H : (0%Z <= x)%Z.

Axiom H1 : (x < n)%Z.

Axiom Requires2 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  (0%Z <= (mixfix_lbrb parent i1))%Z /\ ((mixfix_lbrb parent i1) < n)%Z.

Axiom Requires3 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  ((mixfix_lbrb parent i1) <= i1)%Z.

Parameter r: Numbers.BinNums.Z.

Axiom Ensures : (r = x).

Parameter r1: Numbers.BinNums.Z.

Axiom H2 : (0%Z <= r1)%Z.

Axiom H3 : (r1 < n)%Z.

Axiom LoopInvariant : (r1 <= x)%Z.

Axiom LoopInvariant1 : True.

Axiom H4 : ((mixfix_lbrb parent r1) = r1).

Parameter cur: Numbers.BinNums.Z.

Axiom Ensures1 : (cur = x).

Parameter cur1: Numbers.BinNums.Z.

Parameter parent1: array Numbers.BinNums.Z.

Axiom H5 : ((length parent1) = (length parent)).

Axiom H6 : (0%Z <= r1)%Z.

Axiom H7 : (r1 < n)%Z.

Axiom LoopInvariant2 : ((mixfix_lbrb parent1 r1) = r1).

Axiom H8 : (r1 <= cur1)%Z.

Axiom H9 : (cur1 < n)%Z.

Axiom LoopInvariant3 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  (0%Z <= (mixfix_lbrb parent1 i1))%Z /\ ((mixfix_lbrb parent1 i1) < n)%Z.

Axiom LoopInvariant4 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  ((mixfix_lbrb parent1 i1) <= i1)%Z.

Axiom LoopInvariant5 :
  forall (k1:Numbers.BinNums.Z), (0%Z <= k1)%Z /\ (k1 < r1)%Z ->
  ((mixfix_lbrb parent1 k1) = (mixfix_lbrb parent k1)).

Axiom LoopInvariant6 :
  forall (k1:Numbers.BinNums.Z),
  ((0%Z <= k1)%Z /\ (k1 < n)%Z) /\ ((mixfix_lbrb parent k1) = k1) ->
  ((mixfix_lbrb parent1 k1) = k1).

Axiom H10 : ~ ((mixfix_lbrb parent1 cur1) = r1).

Parameter nxt: Numbers.BinNums.Z.

Axiom Ensures2 : (nxt = (mixfix_lbrb parent1 cur1)).

Parameter parent2: array Numbers.BinNums.Z.

Axiom H11 : ((length parent2) = (length parent1)).

Axiom Ensures3 : ((elts parent2) = (map.Map.set (elts parent1) cur1 r1)).

Axiom Ensures4 : (parent2 = (mixfix_lblsmnrb parent1 cur1 r1)).

Parameter cur2: Numbers.BinNums.Z.

Axiom Ensures5 : (cur2 = nxt).

Axiom LoopInvariant7 : (0%Z <= r1)%Z /\ (r1 < n)%Z.

Axiom LoopInvariant8 : ((mixfix_lbrb parent2 r1) = r1).

Axiom LoopInvariant9 : (r1 <= cur2)%Z /\ (cur2 < n)%Z.

Axiom LoopInvariant10 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  (0%Z <= (mixfix_lbrb parent2 i1))%Z /\ ((mixfix_lbrb parent2 i1) < n)%Z.

Parameter i1: Numbers.BinNums.Z.

Axiom H12 : (0%Z <= i1)%Z.

Axiom H13 : (i1 < n)%Z.

(* Why3 goal *)
Theorem find_compress'vc : ((mixfix_lbrb parent2 i1) <= i1)%Z.
Proof.
  unfold mixfix_lbrb.
  rewrite Ensures3.
  unfold map.Map.set.
  destruct (why_decidable_eq cur1 i1) as [Heq | Hneq].
  - rewrite <- Heq.
    exact H8.
  - exact (LoopInvariant4 i1 (conj H12 H13)).
Qed.
