(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
Require int.Abs.
Require int.EuclideanDivision.
Require map.Map.
Require Import ZArith Lia.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

Axiom array : forall (a:Type), Type.
Parameter array_WhyType :
  forall (a:Type) {a_WT:WhyType a}, WhyType (array a).
Existing Instance array_WhyType.

Parameter elts:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z -> a.

Parameter length:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z.

Axiom array'invariant :
  forall {a:Type} {a_WT:WhyType a},
  forall (self:array a), (0%Z <= (length self))%Z.

(* Why3 assumption *)
Definition mixfix_lbrb {a:Type} {a_WT:WhyType a} (a1:array a)
    (i:Numbers.BinNums.Z) : a :=
  elts a1 i.

Parameter mixfix_lblsmnrb:
  forall {a:Type} {a_WT:WhyType a}, array a -> Numbers.BinNums.Z -> a ->
  array a.

Axiom mixfix_lblsmnrb'spec'0 :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:array a) (i:Numbers.BinNums.Z) (v:a),
  ((length (mixfix_lblsmnrb a1 i v)) = (length a1)).

Axiom mixfix_lblsmnrb'spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (a1:array a) (i:Numbers.BinNums.Z) (v:a),
  ((elts (mixfix_lblsmnrb a1 i v)) = (map.Map.set (elts a1) i v)).

Parameter make:
  forall {a:Type} {a_WT:WhyType a}, Numbers.BinNums.Z -> a -> array a.

Axiom make_spec :
  forall {a:Type} {a_WT:WhyType a},
  forall (n:Numbers.BinNums.Z) (v:a), (0%Z <= n)%Z ->
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z /\ (i < n)%Z ->
   ((mixfix_lbrb (make n v) i) = v)) /\
  ((length (make n v)) = n).

Parameter i: Numbers.BinNums.Z.

Parameter k: Numbers.BinNums.Z.

Parameter parent: array Numbers.BinNums.Z.

Parameter rx: Numbers.BinNums.Z.

Parameter ry: Numbers.BinNums.Z.

Parameter n: Numbers.BinNums.Z.

Axiom Requires : (0%Z <= n)%Z.

Axiom Requires1 : (n <= (length parent))%Z.

Axiom H : (0%Z <= rx)%Z.

Axiom H1 : (rx < n)%Z.

Axiom H2 : (0%Z <= ry)%Z.

Axiom H3 : (ry < n)%Z.

Axiom Requires2 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  (0%Z <= (mixfix_lbrb parent i1))%Z /\ ((mixfix_lbrb parent i1) < n)%Z.

Axiom Requires3 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  ((mixfix_lbrb parent i1) <= i1)%Z.

Axiom Requires4 : ((mixfix_lbrb parent rx) = rx).

Axiom Requires5 : ((mixfix_lbrb parent ry) = ry).

Axiom H4 : ~ (rx < ry)%Z.

Parameter parent1: array Numbers.BinNums.Z.

Axiom H5 : ((length parent1) = (length parent)).

Axiom Ensures : ((elts parent1) = (map.Map.set (elts parent) rx ry)).

Axiom Ensures1 : (parent1 = (mixfix_lblsmnrb parent rx ry)).

Axiom Ensures2 : (0%Z <= ry)%Z /\ (ry < n)%Z.

Axiom Ensures3 : ((mixfix_lbrb parent1 ry) = ry).

Axiom Ensures4 : (ry <= rx)%Z /\ (ry <= ry)%Z.

Axiom Ensures5 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  (0%Z <= (mixfix_lbrb parent1 i1))%Z /\ ((mixfix_lbrb parent1 i1) < n)%Z.

Axiom Ensures6 :
  forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z /\ (i1 < n)%Z ->
  ((mixfix_lbrb parent1 i1) <= i1)%Z.

Parameter k1: Numbers.BinNums.Z.

Axiom H6 : (0%Z <= k1)%Z.

Axiom H7 : (k1 < n)%Z.

Axiom H8 : ~ (k1 = rx).

Axiom H9 : ~ (k1 = ry).

(* Why3 goal *)
Theorem link_roots'vc : ((mixfix_lbrb parent1 k1) = (mixfix_lbrb parent k1)).
Proof.
  unfold mixfix_lbrb.
  rewrite Ensures.
  unfold map.Map.set.
  destruct (why_decidable_eq rx k1) as [Heq | Hneq].
  - exfalso.
    apply H8.
    symmetry.
    exact Heq.
  - reflexivity.
Qed.
