"""Manifest writer/checker tests."""

from __future__ import annotations

from pathlib import Path

from pycsl_emit.ir import Divides, Lit, Result, Var, to_dict

from pycsl_bridge.linker.manifest import (
    Manifest,
    check_manifest,
    read_manifest,
    write_manifest,
)
from pycsl_bridge.reconciler import reconcile_envelopes


def _entry(theorems, ensures):
    return {
        "python_name": "fn",
        "theorems": list(theorems),
        "divides_style": "operational",
        "contract": {
            "requires": [],
            "ensures": [to_dict(e) for e in ensures],
            "assigns": "\\nothing",
            "variant": None,
            "diverges": False,
            "unsupported": [],
        },
    }


def _envelope(provenance, **functions):
    return {
        "schema": "pycsl-ir-dump",
        "version": 1,
        "provenance": provenance,
        "source": f"{provenance}-source",
        "functions": functions,
    }


def test_manifest_round_trip_via_disk(tmp_path: Path):
    rocq = _envelope(
        "rocq2pycsl",
        double=_entry(["double_value", "double_is_even"], [Divides(d=Lit(2), n=Result())]),
    )
    lean = _envelope(
        "lean2pycsl",
        double=_entry(["double_value", "double_is_even"], [Divides(d=Lit(2), n=Result())]),
    )
    rec = reconcile_envelopes(rocq, lean)

    manifest_path = tmp_path / "pycsl-bridge.manifest.toml"
    write_manifest(rec, manifest_path)
    assert manifest_path.exists()

    loaded = read_manifest(manifest_path)
    assert loaded.schema_version == 1
    assert len(loaded.entries) == 1
    e = loaded.entries[0]
    assert e.python == "double"
    assert e.rocq == ("double_value", "double_is_even")
    assert e.lean == ("double_value", "double_is_even")
    assert e.status == "reconciled"


def test_manifest_text_is_human_readable(tmp_path: Path):
    rocq = _envelope("rocq2pycsl", double=_entry(["t"], [Var("p")]))
    lean = _envelope("lean2pycsl", double=_entry(["t"], [Var("p")]))
    rec = reconcile_envelopes(rocq, lean)
    text = Manifest.from_reconciliation(rec).to_toml()
    assert text.startswith("# Auto-generated by pycsl-bridge.")
    assert "schema_version" in text
    assert "[[entry]]" in text
    assert 'python  = "double"' in text


def test_check_manifest_detects_no_drift(tmp_path: Path):
    rocq = _envelope("rocq2pycsl", f=_entry(["t"], [Var("p")]))
    lean = _envelope("lean2pycsl", f=_entry(["t"], [Var("p")]))
    rec = reconcile_envelopes(rocq, lean)
    path = tmp_path / "manifest.toml"
    write_manifest(rec, path)
    assert check_manifest(rec, path) is True


def test_check_manifest_detects_drift(tmp_path: Path):
    rocq = _envelope("rocq2pycsl", f=_entry(["t"], [Var("p")]))
    lean = _envelope("lean2pycsl", f=_entry(["t"], [Var("p")]))
    rec_v1 = reconcile_envelopes(rocq, lean)
    path = tmp_path / "manifest.toml"
    write_manifest(rec_v1, path)

    # Now the rocq side gains a clause that lean lacks → drift.
    rocq_v2 = _envelope("rocq2pycsl", f=_entry(["t", "extra"], [Var("p"), Var("q")]))
    rec_v2 = reconcile_envelopes(rocq_v2, lean)
    assert check_manifest(rec_v2, path) is False


def test_manifest_entries_are_sorted_by_python_qualname(tmp_path: Path):
    rocq = _envelope(
        "rocq2pycsl",
        zebra=_entry(["t"], [Var("p")]),
        apple=_entry(["t"], [Var("p")]),
        mango=_entry(["t"], [Var("p")]),
    )
    lean = _envelope(
        "lean2pycsl",
        zebra=_entry(["t"], [Var("p")]),
        apple=_entry(["t"], [Var("p")]),
        mango=_entry(["t"], [Var("p")]),
    )
    rec = reconcile_envelopes(rocq, lean)
    text = Manifest.from_reconciliation(rec).to_toml()
    positions = [
        text.index('python  = "apple"'),
        text.index('python  = "mango"'),
        text.index('python  = "zebra"'),
    ]
    assert positions == sorted(positions)


def test_manifest_records_disagreement_status():
    rocq = _envelope("rocq2pycsl", f=_entry(["t"], [Var("p")]))
    lean = _envelope("lean2pycsl", f=_entry(["t"], [Var("p"), Var("q")]))
    rec = reconcile_envelopes(rocq, lean)
    text = Manifest.from_reconciliation(rec).to_toml()
    assert 'status  = "disagreement"' in text


def test_check_against_missing_file_returns_false(tmp_path: Path):
    rocq = _envelope("rocq2pycsl", f=_entry(["t"], [Var("p")]))
    lean = _envelope("lean2pycsl", f=_entry(["t"], [Var("p")]))
    rec = reconcile_envelopes(rocq, lean)
    assert check_manifest(rec, tmp_path / "nonexistent.toml") is False
