(* Phase6_WhyML.v — WhyML Subset AST
   Defines the 13-constructor WhyML subset generated by Module 6.
   "Module 6" = `src/pycsl/Module6_WhyMLTranspiler.py` (facade) +
   `src/pycsl/module6_whyml/` (10 emission mixins, post-refactor).
   The key design decision: runtime expression positions use `expr`, while
   spec positions (invariants, variants, assertions, ghost values) use
   `contract_expr`. This mirrors Module 6's output structure exactly and
   makes `gen` (Phase6d_StmtGen) a near-identity function requiring no
   expression translation. *)

Require Import ZArith String List.
Require Import Phase1_AST.
Import ListNotations.
Open Scope string_scope.

(* Exception name type: the four exception flavours Module6 generates *)
Inductive whyml_exc : Type :=
  | ExcReturn               (* SReturn e  → WSeq (WAssign "\result" e) (WRaise ExcReturn) *)
  | ExcBreak                (* SBreak     → WRaise ExcBreak *)
  | ExcContinue             (* SContinue  → WRaise ExcContinue *)
  | ExcNamed (name : ident) (* SRaise exc → WRaise (ExcNamed exc) *).

(* WhyML statement AST — exactly the constructs Module6 can emit.
   Runtime expressions (eval_bool / eval_expr) keep type `expr`.
   Spec expressions (eval_c / eval_v) keep type `contract_expr = ghost_expr`. *)
Inductive whyml_stmt : Type :=
  | WSkip
  (* runtime assignment *)
  | WAssign    (x : ident)   (e : expr)
  | WAugAssign (x : ident)   (op : binop)    (e : expr)
  | WArraySet  (arr : ident) (i : expr)      (v : expr)
  (* control flow *)
  | WSeq       (w1 w2 : whyml_stmt)
  | WIf        (cond : expr) (w_then w_else : whyml_stmt)
  (* invs/vars are lists to mirror Module 6's emission of one
     `invariant {...}` line per source invariant (statements.py:121-136).
     Semantically, the WP rule treats multiple invariants as their
     conjunction (`c_conj` below) and uses the first variant. *)
  | WWhile     (invs : list contract_expr) (vars : list contract_expr)
               (cond : expr)  (body : whyml_stmt)
  (* exception-encoded control flow *)
  | WRaise     (exc : whyml_exc)
  | WTryCatch  (body : whyml_stmt) (exc : ident) (handler : whyml_stmt)
  (* ghost statements — use ghost_expr = contract_expr *)
  | WGhostDecl   (x : ident) (t : ghost_type) (e : ghost_expr)
  | WGhostAssign (x : ident) (t : ghost_type) (op : aug_op) (e : ghost_expr)
  | WLabel     (L : ident)
  (* assertion — spec-level condition *)
  | WAssert    (cond : contract_expr) (msg : string)
  (* assumption — spec-level condition Why3 takes as hypothesis.
     Used in concurrent model for critical-section pre-conditions
     (Module 6 emits `assume { ... }` before the body). *)
  | WAssume    (cond : contract_expr).

(* ===== Helpers for list-shaped invariants/variants =====

   `c_conj` collapses a list of contract_exprs into a single one via
   right-leaning CAnd (CBoolLit true for empty list). Used in WP
   rules that semantically treat multi-invariant whiles as
   conjoined-invariant whiles.

   `c_first` extracts the first variant for the WP termination
   measure (multi-variant lexicographic ordering is a separate
   extension out of scope for this iteration). *)

Fixpoint c_conj (cs : list contract_expr) : contract_expr :=
  match cs with
  | nil => CBoolLit true
  | c :: nil => c
  | c :: rest => CAnd c (c_conj rest)
  end.

Definition c_first (cs : list contract_expr) : contract_expr :=
  match cs with
  | nil => CInt 0
  | c :: _ => c
  end.
