"""Mirror of `src/pycsl/audit_proof.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Set
""  # pycsl
@dataclass
class AuditReport:
    'Outcome of one audit invocation.\n\n    `passes`, `failures`, `skips` are human-readable strings ready to\n    print (one per directive). `exit_code` is 0 on no failures, 1 on\n    any failure. Skips do not affect the exit code in this MVP.\n    '
    passes: List[str] = field(default_factory=list)
    failures: List[str] = field(default_factory=list)
    skips: List[str] = field(default_factory=list)
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    @property
    def exit_code(self) -> int:
        return 0

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def extend(self, other: 'AuditReport') -> None:
        pass


@dataclass
class _Directive:
    prover: str
    qualname: str
    py_file: Path
    line_no: int

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _extract_directives(py_file: Path) -> List[_Directive]:
    return []

_ROCQ_DECL_KEYWORDS = {'Theorem', 'Lemma', 'Definition', 'Inductive', 'Record', 'Fixpoint', 'CoFixpoint', 'Variant', 'Class', 'Structure', 'Corollary', 'Remark', 'Fact', 'Proposition', 'Example'}
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _strip_rocq_comments(text: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _parse_rocq_file(path: Path) -> int:
    return set()

_LEAN_DECL_KEYWORDS = {'theorem', 'lemma', 'def', 'definition', 'structure', 'inductive', 'class', 'abbrev', 'instance'}
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _strip_lean_comments(text: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _parse_lean_file(path: Path) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _index_proofs_dir(proofs_dir: Path, prover: str) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _audit_one_prover(py_file: Path, proofs_dir: Path, prover: str, directives: List[_Directive]) -> AuditReport:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _default_rocq_dir(py_file: Path) -> Path:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _default_lean_dir(py_file: Path) -> Path:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def audit_rocq(py_file: Path, proofs_dir: Optional[Path]=None) -> AuditReport:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def audit_lean(py_file: Path, proofs_dir: Optional[Path]=None) -> AuditReport:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def audit_both(py_file: Path, rocq_dir: Optional[Path]=None, lean_dir: Optional[Path]=None) -> AuditReport:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def print_report(report: AuditReport, header: str) -> None:
    pass

