"""Mirror of `src/pycsl/core_ir_semantic.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import warnings
from typing import Any, Dict, List
from errors import PyCSLSemanticError
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def run_ir_semantic_checks(ir: Any, *, stage: str='ir-semantic') -> None:
    pass

#@ requires True
#@ ensures True
#@ assigns acc
def _collect_call_targets(node: Any, acc: set) -> None:
    if isinstance(node, dict):
        if node.get("type") == "Call":
            f = node.get("func")
            if isinstance(f, str):
                acc.add(f)
                acc.add(f.rsplit(".", 1)[-1])
        for v in node.values():
            _collect_call_targets(v, acc)
    elif isinstance(node, list):
        for v in node:
            _collect_call_targets(v, acc)

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_fresh_globals(ir: Any, stage: str) -> None:
    pass

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_span(func: Any, stage: str) -> None:
    if "line" not in func:
        name = func.get("name", "<anonymous>")
        raise PyCSLSemanticError(
            f"IR function '{name}' carries no source span; a front-end must "
            f"stamp §4.4 spans (line/col) on every node",
            stage=stage,
            code="PYCSL-SEM-SPAN",
        )

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_no_exception(func: Any) -> None:
    from exception_model import KNOWN_EXCEPTIONS  # lazy: keep the import surface small

    contracts = func.get("contracts") or {}
    no_exc = list(contracts.get("no_exception", []) or [])
    no_exc_all = bool(contracts.get("no_exception_all", False))
    raises = contracts.get("raises", []) or []
    raised_names = {r.get("exc_type") for r in raises}

    where = f"function '{func.get('name', '<anonymous>')}' (line {func.get('line', 0)})"

    for name in no_exc:
        if name not in KNOWN_EXCEPTIONS:
            raise PyCSLSemanticError(
                f"{where}: no_exception names unknown exception '{name}'. "
                f"Known: {sorted(KNOWN_EXCEPTIONS)}.",
                code="PYCSL-SEM-NOEXC",
            )
        if name in raised_names:
            raise PyCSLSemanticError(
                f"{where}: contradictory annotations — no_exception {name} "
                f"and raises {{ {name} -> ... }} cannot both apply.",
                code="PYCSL-SEM-NOEXC",
            )
    if no_exc_all and raised_names:
        raise PyCSLSemanticError(
            f"{where}: no_exception \\all requires the raises set to be empty; "
            f"found raises {{ {', '.join(sorted(raised_names))} -> ... }}.",
            code="PYCSL-SEM-NOEXC",
        )

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_assigns_regions(func: Any) -> None:
    where = f"function '{func.get('name', '<anonymous>')}'"
    symtab = func.get("symbol_table") or {}
    for target in func.get("contracts", {}).get("assigns", []) or []:
        if isinstance(target, dict) and target.get("type") == "AssignsRegion":
            base = target.get("base")
            arr_type = symtab.get(base)
            if arr_type is None:
                raise PyCSLSemanticError(
                    f"Assigns region references undefined variable '{base}' in {where}.",
                    code="PYCSL-SEM-ASSIGNS",
                )
            if arr_type not in ("list", "List", "Any"):
                raise PyCSLSemanticError(
                    f"Assigns region on non-list variable '{base}' "
                    f"(type '{arr_type}') in {where}.",
                    code="PYCSL-SEM-ASSIGNS",
                )

_PB_ARRAY_BASE_TYPES = ('list', 'List', 'bytes', 'bytearray', 'Any', None)
_PB_LENGTHLESS_TYPES = ('dict', 'Dict', 'set', 'Set', 'frozenset', 'FrozenSet')
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_contract_exprs(func, known) -> None:
    symtab = func.get("symbol_table") or {}
    fname = func.get("name", "<anonymous>")
    fctx = f"function '{fname}'"
    contracts = func.get("contracts") or {}
    for key in ("requires", "ensures", "assigns", "function_variants"):
        for clause in contracts.get(key, []) or []:
            _pb_expr(clause, fctx, symtab, known)
    _pb_body(func.get("body", []) or [], fname, symtab, known)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _pb_body(stmts: List[Dict[str, Any]], fname, symtab, known) -> None:
    """Walk a statement list, applying the contract-expr checks to while-invariants
    and ghost values with their surface-specific context, recursing into nested bodies."""
    for s in stmts:
        if isinstance(s, dict):
            _pb_stmt(s, fname, symtab, known)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _pb_stmt(s, fname, symtab, known) -> None:
    st = s.get("stmt")
    if st == "While":
        lctx = f"while loop at line {s.get('line', 0)} inside function '{fname}'"
        for clause in (s.get("invariants") or []):
            _pb_expr(clause, lctx, symtab, known)
        for clause in (s.get("variants") or []):
            _pb_expr(clause, lctx, symtab, known)
        _pb_body(s.get("body", []) or [], fname, symtab, known)
    elif st == "For":
        lctx = f"for loop at line {s.get('line', 0)} inside function '{fname}'"
        for clause in (s.get("invariants") or []):
            _pb_expr(clause, lctx, symtab, known)
        for clause in (s.get("variants") or []):
            _pb_expr(clause, lctx, symtab, known)
        _pb_body(s.get("body", []) or [], fname, symtab, known)
    elif st == "GhostAssign":
        _pb_expr(s.get("value"),
                 f"function '{fname}' (ghost '{s.get('target')}')", symtab, known)
    elif st == "GhostArraySet":
        gctx = f"function '{fname}' (ghost '{s.get('target')}[...]')"
        _pb_expr(s.get("index"), gctx, symtab, known)
        _pb_expr(s.get("value"), gctx, symtab, known)
    else:
        for v in s.values():
            _pb_descend(v, fname, symtab, known)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _pb_descend(v, fname, symtab, known) -> None:
    if isinstance(v, dict):
        if "stmt" in v:
            _pb_stmt(v, fname, symtab, known)
        else:
            for x in v.values():
                _pb_descend(x, fname, symtab, known)
    elif isinstance(v, list):
        for x in v:
            _pb_descend(x, fname, symtab, known)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _pb_expr(node, ctx, symtab, known) -> None:
    """Recursively check predicate bases (`\\length`/`\\valid`/`\\separated`) and typed
    quantifier binders in a contract-expr tree, against the surface context. Messages
    reproduce Module 4 verbatim."""
    if isinstance(node, list):
        for x in node:
            _pb_expr(x, ctx, symtab, known)
        return
    if not isinstance(node, dict):
        return
    t = node.get("type")
    if t == "ArrayLen":
        var = node.get("var", "")
        if not str(var).startswith("self.") and var != "\\result":
            typ = symtab.get(var)
            if typ in _PB_LENGTHLESS_TYPES:
                raise PyCSLSemanticError(
                    f"\\length is not supported on the {typ}-typed '{var}' in "
                    f"{ctx}: dicts/sets are modelled as total maps "
                    f"(`map int (option int)`) with no cardinality. Use \\has_key(d, k) "
                    f"for key presence, or a list/array for a length-bearing collection.",
                    code="PYCSL-SEM-PREDBASE",
                )
    elif t == "Valid":
        base = node.get("base")
        arr_type = symtab.get(base)
        if arr_type not in _PB_ARRAY_BASE_TYPES:
            raise PyCSLSemanticError(
                f"\\valid base '{base}' is not a list/bytes parameter "
                f"in {ctx} (got type '{arr_type}').",
                code="PYCSL-SEM-PREDBASE",
            )
    elif t == "Separated":
        for base in (node.get("base1"), node.get("base2")):
            arr_type = symtab.get(base)
            if arr_type not in _PB_ARRAY_BASE_TYPES:
                raise PyCSLSemanticError(
                    f"\\separated base '{base}' is not a list/bytes parameter "
                    f"in {ctx} (got type '{arr_type}').",
                    code="PYCSL-SEM-PREDBASE",
                )
    elif t in ("Forall", "Exists"):
        bt = node.get("binder_type")
        if bt is not None and bt not in known:
            raise PyCSLSemanticError(
                f"Quantifier binder '{node.get('var')}: {bt}' in {ctx} has an "
                f"unresolved type '{bt}'. A typed binder must name a scalar "
                f"(int/bool/str/float) or a declared `#@ datatype` / class — "
                f"it is never silently defaulted to int. "
                f"Known types: {sorted(known)}.",
                code="PYCSL-SEM-QUANTBINDER")
    for v in node.values():
        _pb_expr(v, ctx, symtab, known)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_contract_scope(func, module_constants) -> None:
    symtab = func.get("symbol_table") or {}
    _va_name = func.get("vararg_str_param")
    if _va_name and _va_name not in symtab:
        symtab = {**symtab, _va_name: "tuple"}
    fname = func.get("name", "<anonymous>")
    fctx = f"function '{fname}'"
    contracts = func.get("contracts") or {}
    for key, allow_result in (("requires", False), ("ensures", True),
                              ("assigns", False), ("function_variants", False)):
        for clause in contracts.get(key, []) or []:
            _cs_clause(clause, fctx, allow_result, symtab, module_constants)
    _cs_body(func.get("body", []) or [], fname, symtab, module_constants)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _cs_body(stmts: List[Dict[str, Any]], fname, symtab, mc) -> None:
    for s in stmts:
        if isinstance(s, dict):
            _cs_stmt(s, fname, symtab, mc)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _cs_stmt(s, fname, symtab, mc) -> None:
    st = s.get("stmt")
    if st == "While":
        lctx = f"while loop at line {s.get('line', 0)} inside function '{fname}'"
        for clause in (s.get("invariants") or []):
            _cs_clause(clause, lctx, False, symtab, mc)
        for clause in (s.get("variants") or []):
            _cs_clause(clause, lctx, False, symtab, mc)
        _cs_body(s.get("body", []) or [], fname, symtab, mc)
    elif st == "For":
        lctx = f"for loop at line {s.get('line', 0)} inside function '{fname}'"
        for clause in (s.get("invariants") or []):
            _cs_clause(clause, lctx, False, symtab, mc)
        for clause in (s.get("variants") or []):
            _cs_clause(clause, lctx, False, symtab, mc)
        _cs_body(s.get("body", []) or [], fname, symtab, mc)
    elif st == "GhostAssign":
        _cs_clause(s.get("value"),
                   f"function '{fname}' (ghost '{s.get('target')}')", False, symtab, mc)
    elif st == "GhostArraySet":
        gctx = f"function '{fname}' (ghost '{s.get('target')}[...]')"
        _cs_clause(s.get("index"), gctx, False, symtab, mc)
        _cs_clause(s.get("value"), gctx, False, symtab, mc)
    else:
        for v in s.values():
            _cs_descend(v, fname, symtab, mc)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _cs_descend(v, fname, symtab, mc) -> None:
    if isinstance(v, dict):
        if "stmt" in v:
            _cs_stmt(v, fname, symtab, mc)
        else:
            for x in v.values():
                _cs_descend(x, fname, symtab, mc)
    elif isinstance(v, list):
        for x in v:
            _cs_descend(x, fname, symtab, mc)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _cs_clause(clause, ctx, allow_result, symtab, mc) -> None:
    if clause is None:
        return
    if not allow_result and _contains_result(clause):
        raise PyCSLSemanticError(
            f"Invalid use of '\\result' in {ctx}. It is only allowed in 'ensures'.",
            code="PYCSL-SEM-RESULT",
        )
    for v in _ir_free_vars(clause):
        if v and v not in symtab and v not in mc:
            raise PyCSLSemanticError(
                f"Undefined variable '{v}' referenced in contract for {ctx}. "
                f"Available variables in scope: {list(symtab.keys())}",
                code="PYCSL-SEM-SCOPE",
            )

#@ requires True
#@ ensures True
#@ assigns \nothing
def _ir_free_vars(node):
    """IR port of Module 4's ``extract_variables`` — the free (local-scope) variable
    names a contract expr references. Excludes quantifier binders, ``\\result`` (a
    ``Result`` node, not a ``Var``), and ``self`` fields (``FieldGet``); the string-base
    predicates (``\\length``/``\\valid``/``\\separated``/``\\copy``/assigns-region) carry
    their base as a string, so it is added explicitly before the generic recursion picks
    up nested ``Var`` nodes (lengths, indices, bounds)."""
    if isinstance(node, list):
        out: set = set()
        for x in node:
            out |= _ir_free_vars(x)
        return out
    if not isinstance(node, dict):
        return set()
    t = node.get("type")
    if t == "Var":
        return {node.get("name")}
    if t in ("FieldGet", "Result", "Attribute", "Call", "CallExpr"):
        return set()
    if t == "ArrayLen":
        var = node.get("var", "")
        if str(var).startswith("self.") or var == "\\result":
            return set()
        return {var}
    if t in ("Forall", "Exists"):
        return _ir_free_vars(node.get("body")) - {node.get("var")}
    if t == "ForallItems":
        return ((_ir_free_vars(node.get("body")) - {node.get("key"), node.get("val")})
                | {node.get("coll")})
    base_names: set = set()
    if t == "Valid":
        base_names = {node.get("base")}
    elif t == "Separated":
        base_names = {node.get("base1"), node.get("base2")}
    elif t in ("GhostCopy", "GhostCopyRange"):
        base_names = {node.get("arr")}
    elif t == "AssignsRegion":
        base_names = {node.get("base")}
    out = {b for b in base_names if b}
    for v in node.values():
        out |= _ir_free_vars(v)
    return out

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_subscript_assignments(func) -> None:
    where = f"function '{func.get('name', '<anonymous>')}'"
    symtab = func.get("symbol_table") or {}
    _sa_immutable_walk(func.get("body", []) or [], where, symtab)
    c = func.get("contracts") or {}
    if not (c.get("requires") or c.get("ensures") or c.get("assigns")):
        return
    _sa_walk(func.get("body", []) or [], where, symtab)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _sa_immutable_walk(node, where, symtab) -> None:
    if isinstance(node, dict):
        if node.get("stmt") == "ArraySet":
            arr = node.get("array")
            if isinstance(arr, dict) and arr.get("type") == "Var":
                if symtab.get(arr.get("name")) == "bytes":
                    raise PyCSLSemanticError(
                        f"Subscript assignment to immutable 'bytes' variable "
                        f"'{arr.get('name')}' in {where} — a Python `bytes` object "
                        f"does not support item assignment (TypeError). Use a "
                        f"`bytearray` for a mutable byte buffer.",
                        code="PYCSL-SEM-SUBSCRIPT",
                    )
        for v in node.values():
            _sa_immutable_walk(v, where, symtab)
    elif isinstance(node, list):
        for x in node:
            _sa_immutable_walk(x, where, symtab)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _sa_walk(node, where, symtab) -> None:
    if isinstance(node, dict):
        if node.get("stmt") == "ArraySet":
            arr = node.get("array")
            if isinstance(arr, dict) and arr.get("type") == "Var":
                name = arr.get("name")
                arr_type = symtab.get(name)
                if arr_type is None:
                    raise PyCSLSemanticError(
                        f"Subscript assignment to undefined variable '{name}' in {where}.",
                        code="PYCSL-SEM-SUBSCRIPT",
                    )
                if arr_type not in ("list", "List", "dict", "Dict", "Any"):
                    raise PyCSLSemanticError(
                        f"Subscript assignment to non-list/dict variable '{name}' "
                        f"(type '{arr_type}') in {where}.",
                        code="PYCSL-SEM-SUBSCRIPT",
                    )
        for v in node.values():
            _sa_walk(v, where, symtab)
    elif isinstance(node, list):
        for x in node:
            _sa_walk(x, where, symtab)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_checkpoints(func) -> None:
    where = f"function '{func.get('name', '<anonymous>')}'"
    _cp_walk(func.get("body", []) or [], where)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _cp_walk(node, where) -> None:
    if isinstance(node, dict):
        if node.get("stmt") == "ProofAssert" and _contains_result(node.get("test")):
            raise PyCSLSemanticError(
                f"'\\result' is not allowed in a `#@ {node.get('kind')}` in {where} "
                f"(it is bound only at return; use `ensures` for return values).",
                code="PYCSL-SEM-CHECKPOINT",
            )
        for v in node.values():
            _cp_walk(v, where)
    elif isinstance(node, list):
        for x in node:
            _cp_walk(x, where)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _contains_result(node) -> bool:
    if isinstance(node, dict):
        if node.get("type") == "Result":
            return True
        return any(_contains_result(v) for v in node.values())
    if isinstance(node, list):
        return any(_contains_result(x) for x in node)
    return False

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_ghost_string_ops(func) -> None:
    where = f"function '{func.get('name', '<anonymous>')}'"
    symtab = func.get("symbol_table") or {}
    _gso_walk(func.get("body", []) or [], where, symtab)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _gso_walk(node, where, symtab) -> None:
    if isinstance(node, dict):
        if node.get("stmt") == "GhostAssign":
            op = node.get("op")
            target = node.get("target")
            if op != "=" and symtab.get(target) == "string":
                raise PyCSLSemanticError(
                    f"Ghost string variable '{target}' does not support '{op}' "
                    f"in {where}. "
                    "Use the ^ operator for string concatenation: "
                    f"#@ ghost {target} = {target} ^ expr",
                    code="PYCSL-SEM-GHOSTSTR",
                )
        for v in node.values():
            _gso_walk(v, where, symtab)
    elif isinstance(node, list):
        for x in node:
            _gso_walk(x, where, symtab)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _body_has_diverging_construct(body) -> bool:
    """True iff the IR body contains a loop (``While``/``For``), a critical section
    (``CriticalSection`` — a lock-acquire that may block forever), or a function/method
    call (``{"type": "Call"}`` — recursion or a diverging callee). This is the IR port of
    Module 4's ``ast.walk`` over ``ast.While/For/AsyncFor/Call`` + critical ``with``."""
    found = [False]

    def walk(node):
        if found[0]:
            return
        if isinstance(node, dict):
            if node.get("stmt") in ("While", "For", "CriticalSection"):
                found[0] = True
                return
            if node.get("type") == "Call":
                found[0] = True
                return
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for x in node:
                walk(x)

    walk(body)
    return found[0]

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_diverges(func) -> None:
    if not func.get("diverges"):
        return
    if func.get("lemma"):
        return  # _check_lemma raises the lemma-specific message first
    if _body_has_diverging_construct(func.get("body", []) or []):
        return
    raise PyCSLSemanticError(
        f"`#@ \\diverges` on function '{func.get('name', '<anonymous>')}' is not "
        f"justified: its body has no potentially-diverging construct (no critical "
        f"section / lock-acquire, no loop, no call/recursion). A straight-line body "
        f"provably terminates, so Why3 rejects the `diverges` effect (\"this expression "
        f"does not diverge\"). Remove `#@ \\diverges`, or give the body a construct that "
        f"can actually block or loop.",
        code="PYCSL-SEM-DIVERGES",
    )

#@ requires True
#@ ensures True
#@ assigns \nothing
def _body_has_raise(body) -> bool:
    """True iff the IR body contains a ``Raise`` statement (anywhere, at any depth)."""
    found = [False]

    def walk(node):
        if found[0]:
            return
        if isinstance(node, dict):
            if node.get("stmt") == "Raise":
                found[0] = True
                return
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for x in node:
                walk(x)

    walk(body)
    return found[0]

#@ requires True
#@ ensures True
#@ assigns \nothing
def _body_has_return(body: list) -> bool:
    """True iff the IR body contains a ``Return`` statement (anywhere, at any depth).
    A ``Return`` (with or without a value) is a NORMAL-EXIT path — the very thing a
    ``NoReturn`` function must not have.

    Flat direct-recursive statement-tree existence walk (self-tcb-reduction
    tree-walk-wall): descends every statement-body child list — ``body``/
    ``orelse``/``finalbody`` (While/For/If/Try/With), each ``handlers`` entry's
    body (Try), and each ``cases`` entry's body (Match) — which are the only IR
    positions a ``Return`` statement can occur. Verbatim-identical to the
    self-annotation mirror, where it lowers to the certified stmt_ir
    ``sl_has_return`` catamorphism (byte-diff-0, both provers, axiom-free)."""
    for stmt in body:
        if stmt.get("stmt") == "Return":
            return True
        for key in ("body", "orelse", "finalbody"):
            sub = stmt.get(key)
            if isinstance(sub, list) and _body_has_return(sub):
                return True
        for h in stmt.get("handlers", []):
            if _body_has_return(h.get("body", [])):
                return True
        for c in stmt.get("cases", []):
            if _body_has_return(c.get("body", [])):
                return True
    return False

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_noreturn(func) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_noreturn_names(ir) -> set:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_noreturn_successors(ir) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _noreturn_walk_stmts(stmts, fname, noreturn_names) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _stmt_is_noreturn_call(s, noreturn_names) -> bool:
    return False

#@ requires True
#@ ensures True
#@ assigns \nothing
def _lemma_returns_value(body) -> bool:
    """True iff the IR body contains a ``Return`` statement carrying a non-``None`` value
    (Module 4 walked ``ast.Return`` whose value was neither absent nor the ``None``
    constant)."""
    found = [False]

    def walk(node):
        if found[0]:
            return
        if isinstance(node, dict):
            if node.get("stmt") == "Return":
                v = node.get("value")
                # `return` / `return None` → value is None (no value) or a None constant.
                if v is not None and not (
                        isinstance(v, dict) and v.get("type") in ("None", "CSLNone")):
                    found[0] = True
                    return
            for x in node.values():
                walk(x)
        elif isinstance(node, list):
            for x in node:
                walk(x)

    walk(body)
    return found[0]

#@ requires True
#@ ensures True
#@ assigns \nothing
def _lemma_calls_trusted(body, trusted) -> str:
    hit = [""]

    def walk(node):
        if hit[0]:
            return
        if isinstance(node, dict):
            if node.get("type") == "Call":
                fn = node.get("func")
                if isinstance(fn, str) and fn in trusted:
                    hit[0] = fn
                    return
            for x in node.values():
                walk(x)
        elif isinstance(node, list):
            for x in node:
                walk(x)

    walk(body)
    return hit[0]

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_lemma(func, trusted_funcs) -> None:
    if not func.get("lemma"):
        return
    name = func.get("name", "<anonymous>")
    if func.get("diverges"):
        raise PyCSLSemanticError(
            f"`#@ lemma` '{name}' is also `#@ \\diverges`: a non-terminating "
            f"lemma proves nothing and would be unsound as a fact. Remove one.",
            code="PYCSL-SEM-LEMMA")
    contracts = func.get("contracts") or {}
    if not (contracts.get("ensures") or []):
        raise PyCSLSemanticError(
            f"`#@ lemma` '{name}' has no `#@ ensures`: a lemma must state the "
            f"fact it proves (the conclusion). Add at least one `#@ ensures`.",
            code="PYCSL-SEM-LEMMA")
    ra = func.get("return_annotation")
    if ra not in (None, "None"):
        raise PyCSLSemanticError(
            f"`#@ lemma` '{name}' must be annotated `-> None`: a lemma computes "
            f"nothing (its WhyML result is `unit`); the body is the proof.",
            code="PYCSL-SEM-LEMMA")
    for t in contracts.get("assigns", []) or []:
        if not (isinstance(t, dict) and t.get("type") == "Nothing"):
            raise PyCSLSemanticError(
                f"`#@ lemma` '{name}' must be `assigns \\nothing`: a lemma is "
                f"erased at extraction and may not mutate non-ghost state.",
                code="PYCSL-SEM-LEMMA")
    if _lemma_returns_value(func.get("body", []) or []):
        raise PyCSLSemanticError(
            f"`#@ lemma` '{name}' body must not `return` a value — it is a "
            f"proof (returns unit). Use `pass` for an immediate arm.",
            code="PYCSL-SEM-LEMMA")
    leaked = _lemma_calls_trusted(func.get("body", []) or [], trusted_funcs)
    if leaked:
        raise PyCSLSemanticError(
            f"`#@ lemma` '{name}' calls `\\trusted` function '{leaked}': a "
            f"checked lemma may not rest on an unverified (trusted) fact — that "
            f"would smuggle an unchecked axiom into a 'proved' lemma.",
            code="PYCSL-SEM-LEMMA")

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_mutable_defaults(func) -> None:
    if func.get("has_mutable_default"):
        raise PyCSLSemanticError(
            f"Mutable default argument in function '{func.get('name', '<anonymous>')}': "
            f"a list/dict/set default is a single object shared across all calls (a "
            f"shared-aliasing bug) and is outside PyCSL's value-semantics boundary "
            f"(ownership discipline R2). Use a `None` sentinel and initialise the "
            f"collection in the body.",
            code="PYCSL-SEM-MUTDEFAULT",
        )

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_acts(func) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_happy(ir) -> None:
    pass

#@ requires True
#@ ensures True
#@ assigns written
def _hp_collect_written(node: Any, written: set) -> None:
    if isinstance(node, dict):
        if node.get("stmt") == "ArraySet":
            arr = node.get("array")
            if (isinstance(arr, dict) and arr.get("type") == "FieldGet"
                    and arr.get("object") == "self"):
                written.add(arr.get("field"))
        for v in node.values():
            _hp_collect_written(v, written)
    elif isinstance(node, list):
        for x in node:
            _hp_collect_written(x, written)

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_final(ir) -> None:
    pass

#@ requires True
#@ ensures True
#@ assigns \nothing
def _final_walk_body(stmts: List[Dict[str, Any]], fname, module_finals, class_attr_finals) -> None:
    """Walk a list of IR statements for Final write-policy violations."""
    for s in stmts:
        if isinstance(s, dict):
            _final_check_stmt(s, fname, module_finals, class_attr_finals)

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _final_check_stmt(s, fname, module_finals, class_attr_finals) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_concurrency(ir) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _conc_check_shared_access(var_name, held, fname, shared, write) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _conc_check_reads(node, held, fname, shared) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _conc_stmts(stmts, held, fname, shared, lock_order) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _conc_stmt(s, held, fname, shared, lock_order) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_class_invariants(ir) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_mutex_invariants(ir) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_typeddict_access(func: Any, td_record_names: set) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _typeddict_walk_subscripts(stmts: list, td_vars: set, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _typeddict_check_subscript(sub: dict, td_vars: set, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_namedtuple_access(func: Any, nt_record_names: set, nt_record_arities: dict) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _namedtuple_walk_construction(stmts: list, nt_arities: dict, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _namedtuple_check_call(call: dict, nt_arities: dict, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _namedtuple_walk_subscripts(stmts: list, nt_vars: set, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _namedtuple_check_subscript(sub: dict, nt_vars: set, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_union_narrowing(func: Any) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _union_c8_walk(stmts: list, union_vars: set, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _union_c8_test_references_union_var(test: Any, union_vars: set) -> bool:
    return False

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _union_c8_recognized_guard(test: Any) -> bool:
    return False

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _union_c11_check_dead_arms(match_stmt: Any, fname: str) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_callable_params(func: Any) -> None:
    pass

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_union_gt1(ir: Any) -> None:
    gt1_sites = ir.get("union_gt1_sites") or []
    for site in gt1_sites:
        warnings.warn(
            f"GT1: Union arm `Any` refused (opaque, operation-barren) in "
            f"variant '{site}'. The arm was dropped from the synthesized variant; "
            f"the static plane discharges C2/C3 against non-`Any` arms only.",
            stacklevel=2,
        )

