"""Mirror of `src/pycsl/canonical.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from typing import Dict, List, Tuple
from proof2why3.ir import App, BinOp, BoolLit, Exists, Forall, IntLit, Term, UnaryOp, Unsupported, Var, flatten_arrow_chain, mk_arrow_chain
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def substitute(t: Term, mapping: int) -> Term:
    return None

_NAT_TYPES = {'nat', 'Nat'}
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _expand_nat_to_int(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _alpha_rename(t: Term, counter: List[int]) -> Term:
    return None

#@ requires True
#@ ensures True
#@ assigns \nothing
def alpha_normalize(t: Term) -> Term:
    """Alpha-rename all bound variables to v0, v1, … left-to-right.
    Top-level entry that initializes the counter."""
    counter = [0]
    return _alpha_rename(t, counter)

_FLIP_COMPARISON = {'<=': '>=', '<': '>'}
#@ requires True
#@ ensures True
#@ assigns \nothing
def _flip_comparisons(t: Term) -> Term:
    """Rewrite `a <= b` → `b >= a` and `a < b` → `b > a` recursively."""
    if isinstance(t, (Var, IntLit, BoolLit, Unsupported)):
        return t
    if isinstance(t, App):
        return App(head=t.head,
                   args=tuple(_flip_comparisons(a) for a in t.args))
    if isinstance(t, BinOp):
        if t.op in _FLIP_COMPARISON:
            return BinOp(
                _FLIP_COMPARISON[t.op],
                _flip_comparisons(t.rhs),
                _flip_comparisons(t.lhs),
            )
        return BinOp(t.op, _flip_comparisons(t.lhs), _flip_comparisons(t.rhs))
    if isinstance(t, UnaryOp):
        return UnaryOp(t.op, _flip_comparisons(t.arg))
    if isinstance(t, (Forall, Exists)):
        kind = Forall if isinstance(t, Forall) else Exists
        return kind(binders=t.binders, ty=t.ty, body=_flip_comparisons(t.body))
    raise TypeError(f"_flip_comparisons: unknown {type(t)}")

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _dedup_arrow_chain(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _ac_normalize(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _sort_arrow_hypotheses(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _flatten_foralls(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _camel_to_snake(name: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _normalize_names(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _normalize_type_string(ty: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _iff_app_to_binop(t: Term) -> Term:
    return None

# TERM CARRIER, MODULE-LEVEL (self-tcb-reduction, relaunch #17): CONVERTED, and FULLY
# FAITHFUL. Verbatim body port of the LIVE `canonicalize`. The `val` it replaces was
# `val canonicalize (t: int) : int` — BOTH ends erased — even though this file already
# carries the certified 9-constructor `term` inductive and proves `_flip_comparisons`
# and `alpha_normalize` over it. What blocked it was not the value model: the `-> Term`
# type carrier existed but was TRIPLE-gated, and one of its gates was `@mutable_state`
# CLASS membership, which a plain module-level function can never satisfy. The emitted
# body is now `let canonicalize (t: term) : term`, the guard is the REAL constructor
# discriminant `(match t with Unsupported _ _ -> true | _ -> false end)`, and every
# pipeline step is a real application over `term`. Nothing is erased.
#@ requires True
#@ ensures True
#@ assigns \nothing
def canonicalize(t: Term) -> Term:
    """Apply the full canonicalization pipeline to a Term.

    Idempotent: a second call returns the same Term."""
    if isinstance(t, Unsupported):
        return t
    out = t
    out = _expand_nat_to_int(out)
    out = _flatten_foralls(out)
    out = _flip_comparisons(out)
    out = _dedup_arrow_chain(out)
    out = _ac_normalize(out)
    out = _sort_arrow_hypotheses(out)
    out = _iff_app_to_binop(out)
    out = _normalize_names(out)
    out = alpha_normalize(out)
    return out

