"""Mirror of `src/pycsl/canonical.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from typing import Dict, List, Tuple
from proof2why3.ir import App, BinOp, BoolLit, Exists, Forall, IntLit, Term, UnaryOp, Unsupported, Var, flatten_arrow_chain, mk_arrow_chain
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def substitute(t: Term, mapping: int) -> Term:
    return None

_NAT_TYPES = {'nat', 'Nat'}
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _expand_nat_to_int(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _alpha_rename(t: Term, counter: List[int]) -> Term:
    return None

#@ requires True
#@ ensures True
#@ assigns \nothing
def alpha_normalize(t: Term) -> Term:
    """Alpha-rename all bound variables to v0, v1, … left-to-right.
    Top-level entry that initializes the counter."""
    counter = [0]
    return _alpha_rename(t, counter)

_FLIP_COMPARISON = {'<=': '>=', '<': '>'}
#@ requires True
#@ ensures True
#@ assigns \nothing
def _flip_comparisons(t: Term) -> Term:
    """Rewrite `a <= b` → `b >= a` and `a < b` → `b > a` recursively."""
    if isinstance(t, (Var, IntLit, BoolLit, Unsupported)):
        return t
    if isinstance(t, App):
        return App(head=t.head,
                   args=tuple(_flip_comparisons(a) for a in t.args))
    if isinstance(t, BinOp):
        if t.op in _FLIP_COMPARISON:
            return BinOp(
                _FLIP_COMPARISON[t.op],
                _flip_comparisons(t.rhs),
                _flip_comparisons(t.lhs),
            )
        return BinOp(t.op, _flip_comparisons(t.lhs), _flip_comparisons(t.rhs))
    if isinstance(t, UnaryOp):
        return UnaryOp(t.op, _flip_comparisons(t.arg))
    if isinstance(t, (Forall, Exists)):
        kind = Forall if isinstance(t, Forall) else Exists
        return kind(binders=t.binders, ty=t.ty, body=_flip_comparisons(t.body))
    raise TypeError(f"_flip_comparisons: unknown {type(t)}")

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _dedup_arrow_chain(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _ac_normalize(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _sort_arrow_hypotheses(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _flatten_foralls(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _camel_to_snake(name: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _normalize_names(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _normalize_type_string(ty: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _iff_app_to_binop(t: Term) -> Term:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def canonicalize(t: Term) -> Term:
    return None

