"""Mirror of `src/pycsl/crosscheck.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional
_REPO_ROOT = Path(__file__).resolve().parents[3]
from audit_proof import _extract_directives
from proof2why3.extract import extract_lean_statements, extract_rocq_statements
from proof2why3.normalize import normalize_prover_output, normalize_whyml_axiom
""  # pycsl
@dataclass
class CrossCheckResult:
    'Per-qualname agreement report.'
    qualname: str
    rocq_raw: str = ''
    lean_raw: str = ''
    registry_raw: str = ''
    rocq_norm: str = ''
    lean_norm: str = ''
    registry_norm: str = ''
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def all_agree(self) -> bool:
        norms = [self.rocq_norm, self.lean_norm, self.registry_norm]
        present = [n for n in norms if n]
        if not present:
            return False
        return all(n == present[0] for n in present)

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    @property
    def pairwise(self) -> int:
        return {}

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def diagnostic(self) -> str:
        return ""


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _load_axiom_registry() -> int:
    return {}

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def crosscheck_file(py_file: Path) -> List[CrossCheckResult]:
    return []

#@ requires True
#@ ensures True
#@ assigns \nothing
def _module_namespace_of(rocq_file: Path) -> str:
    """Best-effort guess: a .v file at `0342.proofs/rocq/gcd.v` is
    likely wrapped in `Module Pycsl. Module Reference. Module Gcd.`
    matching the pycsl_target convention. We return the conventional
    prefix `Pycsl.Reference.<TestCapitalized>` where TestCapitalized
    is derived from the .v file stem.

    For non-conventional layouts, return empty string (caller falls
    back to trying all qualnames).
    """
    return ""  # v0: don't filter, let extractor handle all qualnames.

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def main(argv: Optional[List[str]]=None) -> int:
    return 0

