"""Mirror of `src/pycsl/crosscheck.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional
_REPO_ROOT = Path(__file__).resolve().parents[3]
from audit_proof import _extract_directives
from proof2why3.extract import extract_lean_statements, extract_rocq_statements
from proof2why3.normalize import normalize_prover_output, normalize_whyml_axiom
""  # pycsl
@dataclass
class CrossCheckResult:
    'Per-qualname agreement report.'
    qualname: str
    rocq_raw: str = ''
    lean_raw: str = ''
    registry_raw: str = ''
    rocq_norm: str = ''
    lean_norm: str = ''
    registry_norm: str = ''
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def all_agree(self) -> bool:
        norms = [self.rocq_norm, self.lean_norm, self.registry_norm]
        present = [n for n in norms if n]
        if not present:
            return False
        return all(n == present[0] for n in present)

    # CERTIFIED-BOUNDARY (relaunch #16) — [DICT-LITERAL RETURN DECLINES TO THE EMPTY MAP].
    # `@property` support now EMITS this getter (the old [UNEMITTABLE @property] boundary
    # is gone), and the body ports and type-checks. It is NOT converted anyway, because
    # converting it would make the model STRICTLY WORSE: a `map`-returning dict LITERAL
    # declines to `(const (None: option int))` — the EMPTY map — so the `let` would CLAIM
    # that `pairwise` has no keys, a positive FALSE statement, where the `val` it replaces
    # is an unconstrained (havoc) map that claims nothing. A conversion that trades a havoc
    # for a wrong definite value is a faithfulness REGRESSION, not count progress.
    # REOPENING CAPABILITY: lower a string-keyed dict literal to the `map_update_some`
    # chain (`map_update_some (… (const None) "k1" v1 …) "k3" v3`) — `map_update_some` is
    # already declared with `ensures result = Map.set m k v`, so no axiom is involved. Its
    # blast radius is CORPUS-WIDE (every `(const (None: option int))` decline in an 813-file
    # emission), so it owes its own gated increment and its own byte-diff measurement.
    # The twin `crosscheck_ir.pairwise` is co-blocked, and additionally carries a NESTED
    # `def cmp(...)` and `Optional[bool]` values.
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    @property
    def pairwise(self) -> int:
        return {}

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def diagnostic(self) -> str:
        return ""


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _load_axiom_registry() -> int:
    return {}

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def crosscheck_file(py_file: Path) -> List[CrossCheckResult]:
    return []

#@ requires True
#@ ensures True
#@ assigns \nothing
def _module_namespace_of(rocq_file: Path) -> str:
    """Best-effort guess: a .v file at `0342.proofs/rocq/gcd.v` is
    likely wrapped in `Module Pycsl. Module Reference. Module Gcd.`
    matching the pycsl_target convention. We return the conventional
    prefix `Pycsl.Reference.<TestCapitalized>` where TestCapitalized
    is derived from the .v file stem.

    For non-conventional layouts, return empty string (caller falls
    back to trying all qualnames).
    """
    return ""  # v0: don't filter, let extractor handle all qualnames.

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def main(argv: Optional[List[str]]=None) -> int:
    return 0

