"""Mirror of `src/pycsl/crosscheck_ir.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple
_REPO_ROOT = Path(__file__).resolve().parents[3]
from audit_proof import _extract_directives
from proof2why3.canonical import canonicalize
from proof2why3.extract import extract_lean_statements, extract_rocq_statements
from proof2why3.extract_lean_meta import extract_lean_statements_meta, lean_meta_available
from proof2why3.from_lean_json import project_to_ir as lean_ast_to_ir
from proof2why3.from_sexp import project_constr
from proof2why3.ir import App, BinOp, BoolLit, Exists, Forall, IntLit, Term, UnaryOp, Unsupported, Var
from proof2why3.parser import parse_type_expr
from proof2why3.sertop import extract_via_sertop, sertop_available
""  # pycsl
@dataclass
class IRCrossCheckResult:
    'Per-qualname structural cross-check report.'
    qualname: str
    rocq_raw: str = ''
    lean_raw: str = ''
    registry_raw: str = ''
    rocq_ir: Optional[Term] = None
    lean_ir: Optional[Term] = None
    registry_ir: Optional[Term] = None
    rocq_canon: Optional[Term] = None
    lean_canon: Optional[Term] = None
    registry_canon: Optional[Term] = None
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def all_agree(self) -> bool:
        canons = [c for c in
                  (self.rocq_canon, self.lean_canon, self.registry_canon)
                  if c is not None]
        if not canons:
            return False
        return all(c == canons[0] for c in canons)

    # CERTIFIED-BOUNDARY (relaunch #16), RE-MEASURED TWICE IN ONE SESSION and now at its
    # real cause — **[DEGENERATE SYNTHESIZED UNION]**. Two earlier readings were both
    # BROKEN on the way here and both are gone: the dict literal now lowers to a real
    # `map_update_some` chain, and the nested `def cmp(a: Optional[Term], b:
    # Optional[Term])` now gets ONE union type for both parameters (`dedup=True` at the
    # param seam) instead of `_union_cmp_6` / `_union_cmp_7`, so `a == b` is no longer an
    # L3-tc type error. What remains is not a typing problem at all.
    # `Term` is an OPAQUE MARKER CLASS (`class Term: pass`), so the `Optional[Term]` union
    # drops its payload arm and collapses to `type _union_cmp_6 = Arm_6_None` — a type with
    # exactly ONE inhabitant. Therefore `a is None` lowers to a test that is ALWAYS TRUE
    # (lesson (bl): a guard lowering to a literal signals a modelled-away optional), the
    # else-branch is unreachable, and the converted `cmp` would return `None` on every
    # path. The `let` would then CLAIM that all three `pairwise` values are `None` — a
    # positive FALSE statement, where the `val` it replaces is an unconstrained havoc that
    # claims nothing. DECLINED under lesson (ca): a conversion must not trade a havoc for a
    # wrong definite value.
    # REOPENING CAPABILITY: give a synthesized `Optional[X]` union a `Some` arm carrying an
    # OPAQUE payload when `X` is an unmodelled class, instead of dropping the arm. That
    # makes the presence test real and the else-branch reachable; `a == b` would then be an
    # honest uninterpreted equality on the opaque payload.
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    @property
    def pairwise(self) -> Dict[str, Optional[bool]]:
        return {}

    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def any_unsupported(self) -> bool:
        return any(isinstance(c, Unsupported)
                   for c in (self.rocq_canon, self.lean_canon,
                             self.registry_canon)
                   if c is not None)

    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def all_present_unsupported(self) -> bool:
        canons = [c for c in (self.rocq_canon, self.lean_canon,
                              self.registry_canon) if c is not None]
        if not canons:
            return False
        return all(isinstance(c, Unsupported) for c in canons)

    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def registry_skipped(self) -> bool:
        return (not self.registry_raw) and (
            self.rocq_canon is not None or self.lean_canon is not None
        )

    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def provers_agree(self) -> bool:
        if self.rocq_canon is None or self.lean_canon is None:
            return True
        return self.rocq_canon == self.lean_canon

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def diagnostic(self) -> str:
        return ""


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _load_axiom_registry() -> int:
    return {}

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _preprocess_whyml(body: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def crosscheck_file_ir(py_file: Path) -> List[IRCrossCheckResult]:
    return []

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def main(argv: Optional[List[str]]=None) -> int:
    return 0

