"""Mirror of `src/pycsl/emit_why3.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from proof2why3.ir import App, BinOp, BoolLit, Exists, Forall, IntLit, Term, UnaryOp, Unsupported, Var
_PREC_TOP = 0
_PREC_ARROW = 1
_PREC_OR = 2
_PREC_AND = 3
_PREC_CMP = 4
_PREC_ADD = 5
_PREC_MUL = 6
_PREC_APP = 7
_PREC_ATOM = 8
_BINOP_PREC = {'->': _PREC_ARROW, '\\/': _PREC_OR, '/\\': _PREC_AND, '=': _PREC_CMP, '>': _PREC_CMP, '>=': _PREC_CMP, '<': _PREC_CMP, '<=': _PREC_CMP, '<>': _PREC_CMP, '!=': _PREC_CMP, '+': _PREC_ADD, '-': _PREC_ADD, '*': _PREC_MUL}
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _pp(t: Term, parent_prec: int) -> str:
    return ""

#@ requires True
#@ ensures True
#@ assigns \nothing
def ir_to_whyml_axiom_body(term: Term) -> str:
    """Serialize a Term back to a WhyML axiom-body string.

    The output is suitable for direct inclusion as a value in
    `_AXIOM_REGISTRY` (Module 6 preamble). Round-trip through
    `parse_type_expr` + `canonicalize` produces the same canonical
    form as the input."""
    return _pp(term, _PREC_TOP)

#@ requires True
#@ ensures True
#@ assigns \nothing
def contains_unsupported(term: Term) -> bool:
    """True if any sub-term is an `Unsupported` leaf. Used by the
    merge tool to skip non-round-trippable entries rather than
    overwriting the existing hand-curated body with a sentinel."""
    if isinstance(term, Unsupported):
        return True
    if isinstance(term, (Var, IntLit, BoolLit)):
        return False
    if isinstance(term, App):
        return any(contains_unsupported(a) for a in term.args)
    if isinstance(term, BinOp):
        return contains_unsupported(term.lhs) or contains_unsupported(term.rhs)
    if isinstance(term, UnaryOp):
        return contains_unsupported(term.arg)
    if isinstance(term, (Forall, Exists)):
        return contains_unsupported(term.body)
    raise TypeError(f"contains_unsupported: unknown {type(term)}")

