"""Mirror of `src/pycsl/extract_lean_meta.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import json
import os
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional
_REPO_ROOT = Path(__file__).resolve().parents[3]
_META_SCRIPT = _REPO_ROOT / 'bin' / 'proof2why3-lean-extract.lean'
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def lean_meta_available(proofs_dir: Path) -> bool:
    return False

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def extract_lean_statements_meta(proof_file: Path, qualnames: List[str]) -> int:
    return {}

