"""Mirror of `src/pycsl/from_lean_json.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from typing import Any, Dict, List, Optional, Tuple
from proof2why3.ir import App, BinOp, BoolLit, Exists, Forall, IntLit, Term, UnaryOp, Unsupported, Var
_OP_TABLE_BINOP: int = {'HAdd.hAdd': ('+', 4), 'HSub.hSub': ('-', 4), 'HMul.hMul': ('*', 4), 'HDiv.hDiv': ('/', 4), 'LE.le': ('>=', 2), 'LT.lt': ('>', 2), 'GE.ge': ('>=', 2), 'GT.gt': ('>', 2), 'Eq': ('=', 1), 'Ne': ('<>', 1), 'And': ('/\\\\', 0), 'Or': ('\\/', 0), 'Iff': ('iff', 0)}
_FLIP_DIRECTION = {'LE.le': True, 'LT.lt': True, 'GE.ge': False, 'GT.gt': False}
_PREFIX_STRIPS: List[int] = [('Nat.gcd', 'gcd'), ('Nat.modulo', 'mod'), ('Nat.add', 'add'), ('Nat.mul', 'mul'), ('Nat.sub', 'sub'), ('Nat.le', '<='), ('Nat.lt', '<'), ('Iff', 'iff')]
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _body_references_bvar_0(ast: Any, depth: int=0) -> bool:
    return False

#@ requires True
#@ ensures True
#@ assigns \nothing
def _strip_const_name(name: str) -> str:
    for src, dst in _PREFIX_STRIPS:
        if name == src:
            return dst
    return name

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _linearize_app(ast: int) -> Tuple[int, List[int]]:
    return ([], {})

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _is_ofnat_lit(ast: int) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def project_to_ir(ast: int, ctx: Optional[List[str]]=None) -> Term:
    return None

