"""Mirror of `src/pycsl/ir.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Tuple
""  # pycsl
@dataclass(frozen=True)
class Var:
    'A free or bound variable reference.'
    name: str
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        return self.name


@dataclass(frozen=True)
class IntLit:
    value: int
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        return str(self.value)


@dataclass(frozen=True)
class BoolLit:
    value: bool
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        return "true" if self.value else "false"


@dataclass(frozen=True)
class App:
    'N-ary application `head arg0 arg1 …`.'
    head: str
    args: Tuple['Term', ...]
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        if not self.args:
            return self.head
        return f"({self.head} {' '.join(a.pp() for a in self.args)})"


@dataclass(frozen=True)
class BinOp:
    'Binary operator. The operator is a string token in a small\n    canonical set: `=`, `>`, `>=`, `<>`, `+`, `-`, `*`, `mod`, `\\/`,\n    `/\\`, `->`, `iff`. We use BinOp for both arithmetic and logical\n    operators; the canonicalization step folds them into n-ary\n    sorted forms via App nodes for AC operators.'
    op: str
    lhs: 'Term'
    rhs: 'Term'
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        return f"({self.lhs.pp()} {self.op} {self.rhs.pp()})"


@dataclass(frozen=True)
class UnaryOp:
    'Unary operator (currently only logical `not` and arithmetic `-`).'
    op: str
    arg: 'Term'
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        return f"({self.op} {self.arg.pp()})"


@dataclass(frozen=True)
class Forall:
    'Universal quantifier with a flat binder list `forall x1 x2 … : ty, body`.\n\n    The binder type `ty` is a string token from a small canonical set\n    (`int`, `nat`, `bool`, …); nat/Nat are normalized to int with\n    side conditions in Phase 3b.'
    binders: Tuple[str, ...]
    ty: str
    body: 'Term'
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        binders = " ".join(self.binders)
        return f"(forall {binders} : {self.ty}, {self.body.pp()})"


@dataclass(frozen=True)
class Exists:
    binders: Tuple[str, ...]
    ty: str
    body: 'Term'
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        binders = " ".join(self.binders)
        return f"(exists {binders} : {self.ty}, {self.body.pp()})"


@dataclass(frozen=True)
class Unsupported:
    "A leaf for constructs the parser can't represent. Carries the\n    raw token slice for diagnostic purposes."
    reason: str
    raw: str
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def pp(self) -> str:
        return f"<UNSUPPORTED: {self.reason}>"


Term = 0  # pycsl: stubbed type alias (string form unsupported)
#@ requires True
#@ ensures True
#@ assigns \nothing
def mk_arrow_chain(hyps: List[Term], conclusion: Term) -> Term:
    out: Term = conclusion
    for h in reversed(hyps):
        out = BinOp("->", h, out)
    return out

#@ requires True
#@ ensures True
#@ assigns \nothing
def flatten_arrow_chain(t: Term) -> Tuple[List[Term], Term]:
    hyps: List[Term] = []
    cur = t
    while isinstance(cur, BinOp) and cur.op == "->":
        hyps.append(cur.lhs)
        cur = cur.rhs
    return hyps, cur

#@ requires True
#@ ensures True
#@ assigns \nothing
def free_vars(t: Term) -> set:
    if isinstance(t, Var):
        return {t.name}
    if isinstance(t, (IntLit, BoolLit, Unsupported)):
        return set()
    if isinstance(t, App):
        out = set()
        for a in t.args:
            out |= free_vars(a)
        return out
    if isinstance(t, BinOp):
        return free_vars(t.lhs) | free_vars(t.rhs)
    if isinstance(t, UnaryOp):
        return free_vars(t.arg)
    if isinstance(t, (Forall, Exists)):
        return free_vars(t.body) - set(t.binders)
    raise TypeError(f"free_vars: unknown term type {type(t)}")

