"""Mirror of `src/pycsl/normalize.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import re
from typing import List, Tuple
_UNICODE_OPS = {'∀': 'forall', '→': '->', '≥': '>=', '≤': '<=', '∨': '\\/', '∧': '/\\\\', '≠': '<>', '¬': 'not', '≡': '='}
_PREFIX_STRIPS: List[int] = [('PeanoNat.Nat.gcd', 'gcd'), ('PeanoNat.Nat.modulo', 'mod'), ('PeanoNat.Nat.add', 'add'), ('PeanoNat.Nat.mul', 'mul'), ('PeanoNat.Nat.sub', 'sub'), ('Nat.gcd', 'gcd'), ('Nat.modulo', 'mod'), ('Nat.mod', 'mod'), ('Nat.add', 'add'), ('Nat.mul', 'mul'), ('Nat.sub', 'sub'), ('BinNat.N.gcd', 'gcd'), ('BinNat.N.modulo', 'mod'), ('Init.Nat.gcd', 'gcd')]
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def normalize_prover_output(s: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _strip_all_parens(s: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _nat_to_int_with_sidecond(s: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _expand_anon_binders(s: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _alpha_rename(s: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def normalize_whyml_axiom(body: str) -> str:
    return ""

