"""Mirror of `src/pycsl/parser.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import re
from dataclasses import dataclass
from typing import List, Optional, Tuple
from proof2why3.ir import App, BinOp, BoolLit, Exists, Forall, IntLit, Term, UnaryOp, Unsupported, Var, mk_arrow_chain
_UNICODE_OPS = {'∀': 'forall ', '∃': 'exists ', '→': '->', '≥': '>=', '≤': '<=', '∨': '\\/', '∧': '/\\\\', '≠': '<>', '¬': ' not ', '≡': '='}
_LIBRARY_PREFIX_STRIPS: List[int] = [('PeanoNat.Nat.gcd', 'gcd'), ('PeanoNat.Nat.modulo', 'mod'), ('PeanoNat.Nat.add', 'add'), ('PeanoNat.Nat.mul', 'mul'), ('PeanoNat.Nat.sub', 'sub'), ('Nat.gcd', 'gcd'), ('Nat.modulo', 'mod'), ('Nat.mod', 'mod'), ('Nat.add', 'add'), ('Nat.mul', 'mul'), ('Nat.sub', 'sub'), ('BinNat.N.gcd', 'gcd'), ('BinNat.N.modulo', 'mod'), ('PyCSL.AST.Expr', 'Expr')]
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def normalize_surface(s: str) -> str:
    return ""

""  # pycsl
@dataclass
class Token:
    kind: str
    value: str
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __repr__(self) -> str:
        return ""


_OP_TOKENS = ['->', '>=', '<=', '<>', '==', '!=', '\\/', '/\\\\', '=', '>', '<', '+', '-', '*']
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def lex(s: str) -> List[Token]:
    return []

_LOGICAL_DISJ_OPS = {'\\/'}
_LOGICAL_CONJ_OPS = {'/\\\\'}
_COMPARISON_OPS = {'=', '>=', '<=', '>', '<', '<>', '!=', '=='}
_ARITH_ADD_OPS = {'+', '-'}
_ARITH_MUL_OPS = {'*'}
_KNOWN_FN_HEADS = {'gcd', 'mod', 'add', 'mul', 'sub', 'DecidableEq', 'bit_and', 'struct_pack_i1a1', 'struct_unpack_i1a1', 'struct_pack_i2', 'struct_unpack_i2', 'struct_pack_i18', 'struct_unpack_i18'}
# Mirror-only infra shim (see bin/self-annotate-mirror-check.sh MIRROR_ONLY): marks the
# token-cursor `_Parser` as a stateful record so its `toks`/`pos` fields lower to
# `mutable toks: array token` / `mutable pos: int`.
def mutable_state(cls):
    return cls


# NOTE the invariant is `0 <= self.pos` ONLY. Unlike the two frontend cursors, the live
# `take` steps `self.pos` UNGUARDED, so `self.pos < \length(self.toks)` is genuinely NOT
# an invariant of this class — the bound is `take`'s PRECONDITION instead (the live
# method is partial: it raises IndexError past the end).
#@ class invariant 0 <= self.pos
@mutable_state
class _Parser:
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __init__(self, tokens: List[Token]) -> None:
        self.toks: List[Token] = tokens
        self.pos: int = 0

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def peek(self, offset: int=0) -> Optional[Token]:
        return None

    #@ requires self.pos < \length(self.toks)
    #@ ensures True
    #@ assigns self.pos
    def take(self) -> Token:
        t = self.toks[self.pos]
        self.pos += 1
        return t

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def expect(self, kind: str, value: Optional[str]=None) -> Token:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_expr(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_quant(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_implication(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_disjunction(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_conjunction(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_comparison(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_arith_add(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_arith_mul(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_atom_application(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def parse_atom(self) -> Term:
        return None


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def parse_type_expr(s: str) -> Term:
    return None

