"""Mirror of `src/pycsl/parser.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import re
from dataclasses import dataclass
from typing import List, Optional, Tuple
from proof2why3.ir import App, BinOp, BoolLit, Exists, Forall, IntLit, Term, UnaryOp, Unsupported, Var, mk_arrow_chain
_UNICODE_OPS = {'∀': 'forall ', '∃': 'exists ', '→': '->', '≥': '>=', '≤': '<=', '∨': '\\/', '∧': '/\\\\', '≠': '<>', '¬': ' not ', '≡': '='}
_LIBRARY_PREFIX_STRIPS: List[int] = [('PeanoNat.Nat.gcd', 'gcd'), ('PeanoNat.Nat.modulo', 'mod'), ('PeanoNat.Nat.add', 'add'), ('PeanoNat.Nat.mul', 'mul'), ('PeanoNat.Nat.sub', 'sub'), ('Nat.gcd', 'gcd'), ('Nat.modulo', 'mod'), ('Nat.mod', 'mod'), ('Nat.add', 'add'), ('Nat.mul', 'mul'), ('Nat.sub', 'sub'), ('BinNat.N.gcd', 'gcd'), ('BinNat.N.modulo', 'mod'), ('PyCSL.AST.Expr', 'Expr')]
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def normalize_surface(s: str) -> str:
    return ""

""  # pycsl
@dataclass
class Token:
    kind: str
    value: str
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __repr__(self) -> str:
        return ""


_OP_TOKENS = ['->', '>=', '<=', '<>', '==', '!=', '\\/', '/\\\\', '=', '>', '<', '+', '-', '*']
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def lex(s: str) -> List[Token]:
    return []

_LOGICAL_DISJ_OPS = {'\\/'}
_LOGICAL_CONJ_OPS = {'/\\\\'}
_COMPARISON_OPS = {'=', '>=', '<=', '>', '<', '<>', '!=', '=='}
_ARITH_ADD_OPS = {'+', '-'}
_ARITH_MUL_OPS = {'*'}
_KNOWN_FN_HEADS = {'gcd', 'mod', 'add', 'mul', 'sub', 'DecidableEq', 'bit_and', 'struct_pack_i1a1', 'struct_unpack_i1a1', 'struct_pack_i2', 'struct_unpack_i2', 'struct_pack_i18', 'struct_unpack_i18'}
# Mirror-only infra shim (see bin/self-annotate-mirror-check.sh MIRROR_ONLY): marks the
# token-cursor `_Parser` as a stateful record so its `toks`/`pos` fields lower to
# `mutable toks: array token` / `mutable pos: int`.
def mutable_state(cls):
    return cls


# NOTE the invariant is `0 <= self.pos` ONLY. Unlike the two frontend cursors, the live
# `take` steps `self.pos` UNGUARDED, so `self.pos < \length(self.toks)` is genuinely NOT
# an invariant of this class — the bound is `take`'s PRECONDITION instead (the live
# method is partial: it raises IndexError past the end).
#@ class invariant 0 <= self.pos
@mutable_state
class _Parser:
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __init__(self, tokens: List[Token]) -> None:
        self.toks: List[Token] = tokens
        self.pos: int = 0

    # `offset >= 0` is a genuine PARTIALITY boundary, read off the live body: the read
    # `self.toks[idx]` is guarded ONLY from above (`idx < len(self.toks)`), so a negative
    # `offset` makes `idx` negative and Python silently reads from the END of the list —
    # a different token than "the one `offset` ahead". Every live call site in this file
    # passes the default `0`. Not a convenience narrowing.
    #@ requires offset >= 0
    #@ ensures True
    # CURSOR INTERFACE (L13): the Some arm is returned ONLY from inside the
    # `idx < len(self.toks)` guard, so a non-None result WITNESSES that the cursor
    # (plus offset) is in range. This is what lets a caller that has tested
    # `t is not None` discharge `take`'s `requires self.pos < \length(self.toks)`.
    # PROVED here (peek is converted), so it costs no TCB.
    #@ ensures \result != None ==> self.pos + offset < \length(self.toks)
    #@ assigns \nothing
    def peek(self, offset: int = 0) -> Optional[Token]:
        idx = self.pos + offset
        if idx < len(self.toks):
            return self.toks[idx]
        return None

    #@ requires self.pos < \length(self.toks)
    #@ ensures True
    # CURSOR INTERFACE (L13): `take` steps the cursor by EXACTLY one (unguarded
    # `self.pos += 1`), which is the strict progress every loop variant in the nest
    # needs. With the precondition it also gives `self.pos <= \length(self.toks)`.
    # PROVED (take is converted) -> zero TCB.
    #@ ensures self.pos == \old(self.pos) + 1
    #@ assigns self.pos
    def take(self) -> Token:
        t = self.toks[self.pos]
        self.pos += 1
        return t

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns self.pos
    def expect(self, kind: str, value: Optional[str]=None) -> Token:
        return None

    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13): monotone + in-range. PROVED here (the member is
    # converted), so it costs ZERO TCB — unlike the same clause on a `\trusted`
    # stub, which would be an assumed reviewer assertion.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_expr(self) -> Term:
        t = self.peek()
        if t is not None and t.kind == "IDENT" and t.value in ("forall", "exists"):
            return self.parse_quant()
        return self.parse_implication()

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13) — an ASSUMED interface on a still-`\trusted` stub, i.e.
    # a REAL (small) TCB addition, justified by reading the live body: every cursor
    # motion in `_Parser` goes through `take`, whose `self.pos += 1` is monotone, and
    # whose partiality (`self.toks[self.pos]` raises IndexError past the end) keeps
    # `self.pos <= len(self.toks)` on every NORMAL-return path. There is no
    # backtracking site anywhere in this class (no `_try`-style save/restore, no
    # direct `self.pos = <expr>` outside `__init__` and `take`). Retire this
    # assumption by CONVERTING the stub.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_quant(self) -> Term:
        return None

    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13): monotone + in-range. PROVED here (the member is
    # converted), so it costs ZERO TCB — unlike the same clause on a `\trusted`
    # stub, which would be an assumed reviewer assertion.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ \variant \length(self.toks) - self.pos
    #@ assigns self.pos
    def parse_implication(self) -> Term:
        lhs = self.parse_disjunction()
        t = self.peek()
        if t is not None and t.kind == "OP" and t.value == "->":
            self.take()
            rhs = self.parse_implication()
            return BinOp("->", lhs, rhs)
        return lhs

    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13): monotone + in-range. PROVED here (the member is
    # converted), so it costs ZERO TCB — unlike the same clause on a `\trusted`
    # stub, which would be an assumed reviewer assertion.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_disjunction(self) -> Term:
        out = self.parse_conjunction()
        # The RANGE invariant alone is not enough: the function's own
        # `ensures self.pos >= \old(self.pos)` has to survive the loop, and a loop
        # invariant is the only place to carry a relation back to function entry.
        #@ loop invariant self.pos >= \old(self.pos)
        #@ loop invariant 0 <= self.pos and self.pos <= \length(self.toks)
        #@ loop variant \length(self.toks) - self.pos
        while True:
            t = self.peek()
            if t is None or t.kind != "OP" or t.value not in _LOGICAL_DISJ_OPS:
                break
            op = self.take().value
            rhs = self.parse_conjunction()
            out = BinOp(op, out, rhs)
        return out

    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13): monotone + in-range. PROVED here (the member is
    # converted), so it costs ZERO TCB — unlike the same clause on a `\trusted`
    # stub, which would be an assumed reviewer assertion.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_conjunction(self) -> Term:
        out = self.parse_comparison()
        # The RANGE invariant alone is not enough: the function's own
        # `ensures self.pos >= \old(self.pos)` has to survive the loop, and a loop
        # invariant is the only place to carry a relation back to function entry.
        #@ loop invariant self.pos >= \old(self.pos)
        #@ loop invariant 0 <= self.pos and self.pos <= \length(self.toks)
        #@ loop variant \length(self.toks) - self.pos
        while True:
            t = self.peek()
            if t is None or t.kind != "OP" or t.value not in _LOGICAL_CONJ_OPS:
                break
            op = self.take().value
            rhs = self.parse_comparison()
            out = BinOp(op, out, rhs)
        return out

    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13): monotone + in-range. PROVED here (the member is
    # converted), so it costs ZERO TCB — unlike the same clause on a `\trusted`
    # stub, which would be an assumed reviewer assertion.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_comparison(self) -> Term:
        lhs = self.parse_arith_add()
        t = self.peek()
        if t is not None and t.kind == "OP" and t.value in _COMPARISON_OPS:
            op = self.take().value
            mid = self.parse_arith_add()
            t2 = self.peek()
            if t2 is not None and t2.kind == "OP" and t2.value in _COMPARISON_OPS:
                op2 = self.take().value
                rhs = self.parse_arith_add()
                return BinOp(r"/\\", BinOp(op, lhs, mid), BinOp(op2, mid, rhs))
            return BinOp(op, lhs, mid)
        return lhs

    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13): monotone + in-range. PROVED here (the member is
    # converted), so it costs ZERO TCB — unlike the same clause on a `\trusted`
    # stub, which would be an assumed reviewer assertion.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_arith_add(self) -> Term:
        out = self.parse_arith_mul()
        # The RANGE invariant alone is not enough: the function's own
        # `ensures self.pos >= \old(self.pos)` has to survive the loop, and a loop
        # invariant is the only place to carry a relation back to function entry.
        #@ loop invariant self.pos >= \old(self.pos)
        #@ loop invariant 0 <= self.pos and self.pos <= \length(self.toks)
        #@ loop variant \length(self.toks) - self.pos
        while True:
            t = self.peek()
            if t is None or t.kind != "OP" or t.value not in _ARITH_ADD_OPS:
                break
            op = self.take().value
            rhs = self.parse_arith_mul()
            out = BinOp(op, out, rhs)
        return out

    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13): monotone + in-range. PROVED here (the member is
    # converted), so it costs ZERO TCB.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_arith_mul(self) -> Term:
        out = self.parse_atom_application()
        #@ loop invariant self.pos >= \old(self.pos)
        #@ loop invariant 0 <= self.pos and self.pos <= \length(self.toks)
        #@ loop variant \length(self.toks) - self.pos
        while True:
            t = self.peek()
            if t is None:
                break
            if t.kind == "OP" and t.value in _ARITH_MUL_OPS:
                op = self.take().value
                rhs = self.parse_atom_application()
                out = BinOp(op, out, rhs)
                continue
            # `mod` as identifier-infix (Lean-style `a mod b` after
            # `%` → `mod` normalization). Folded into App(mod, ...)
            # for shape parity with Rocq's `mod a b` prefix form.
            if t.kind == "IDENT" and t.value == "mod":
                self.take()
                rhs = self.parse_atom_application()
                out = App(head="mod", args=(out, rhs))
                continue
            break
        return out

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13) — an ASSUMED interface on a still-`\trusted` stub, i.e.
    # a REAL (small) TCB addition, justified by reading the live body: every cursor
    # motion in `_Parser` goes through `take`, whose `self.pos += 1` is monotone, and
    # whose partiality (`self.toks[self.pos]` raises IndexError past the end) keeps
    # `self.pos <= len(self.toks)` on every NORMAL-return path. There is no
    # backtracking site anywhere in this class (no `_try`-style save/restore, no
    # direct `self.pos = <expr>` outside `__init__` and `take`). Retire this
    # assumption by CONVERTING the stub.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_atom_application(self) -> Term:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    # CURSOR INTERFACE (L13) — an ASSUMED interface on a still-`\trusted` stub, i.e.
    # a REAL (small) TCB addition, justified by reading the live body: every cursor
    # motion in `_Parser` goes through `take`, whose `self.pos += 1` is monotone, and
    # whose partiality (`self.toks[self.pos]` raises IndexError past the end) keeps
    # `self.pos <= len(self.toks)` on every NORMAL-return path. There is no
    # backtracking site anywhere in this class (no `_try`-style save/restore, no
    # direct `self.pos = <expr>` outside `__init__` and `take`). Retire this
    # assumption by CONVERTING the stub.
    #@ ensures self.pos >= \old(self.pos)
    #@ ensures self.pos <= \length(self.toks)
    #@ assigns self.pos
    def parse_atom(self) -> Term:
        return None


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def parse_type_expr(s: str) -> Term:
    return None

