"""Mirror of `src/pycsl/sertop.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import os
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Tuple
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def sertop_available() -> bool:
    return False

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def sertop_version() -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _sexp_tokens(s: str) -> Iterator[str]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _sexp_parse(tokens: List[str]) -> object:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def parse_sexp(s: str) -> object:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _process_sertop_line(line: str, payloads_by_tag: int) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _extract_stmid(added_payload: object) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def run_sertop_batch(load_paths, cwd: Path, require_module: str, qualnames: List[str], timeout_s: float=60.0, require_prefix: Optional[str]=None) -> int:
    return {}

""  # pycsl
@dataclass
class SertopSession:
    'Convenience wrapper for callers that need a long-lived session.\n\n    Internally delegates to `run_sertop_batch` for each query group\n    (which restarts sertop per group). For multi-query scenarios\n    `run_sertop_batch` is more efficient.'
    load_paths: List[Path] = field(default_factory=list)
    cwd: Optional[Path] = None
    proc: Optional[subprocess.Popen] = None
    seq: int = 0
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __enter__(self) -> 'SertopSession':
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def type_of_batch(self, require_module: str, qualnames: List[str]) -> int:
        return {}


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def extract_via_sertop(proof_file: Path, qualnames: List[str]) -> int:
    return {}

