"""Mirror of `src/pycsl/ConcurrencyChecker.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from frontend import pure_ast as ast
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set
from errors import PyCSLSemanticError
_ERR_UNPROTECTED_DECL = 'declared shared but has no protected_by mutex. All accesses are potential data races.'
_ERR_UNPROTECTED_WRITE = "Unprotected %s shared variable '%s' (requires '%s')"
_TRUSTED_CONCURRENT_TYPES = {'queue.Queue', 'Queue', 'threading.Lock', 'Lock', 'threading.RLock', 'RLock', 'threading.Semaphore', 'Semaphore', 'threading.Event', 'Event', 'threading.Condition', 'Condition', 'threading.Barrier', 'Barrier'}
_TRUSTED_ATTRIBUTES = {'put', 'get', 'acquire', 'release', 'wait', 'set', 'notify', 'notify_all', 'is_set'}
""  # pycsl
@dataclass
class ConcurrencyWarning:
    kind: str
    message: str
    function: str = ''
    line: int = 0

class ConcurrencyChecker:
    'Walk the annotated AST and emit ConcurrencyWarning objects.'
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __init__(self, tree: ast.AST, *, strict_mode: bool=False, filename: str='<input>') -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def check(self) -> List[ConcurrencyWarning]:
        return []

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _check_function(self, func: ast.FunctionDef) -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _walk_body(self, stmts: list, held: int, func_name: str) -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _walk_stmt(self, node: ast.AST, held: int, func_name: str) -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _warn_if_unprotected(self, var: str, held: int, func_name: str, line: int, write: bool) -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def summary(self) -> str:
        return ""


