"""Mirror of `src/pycsl/ConcurrencyChecker.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from frontend import pure_ast as ast
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set
from errors import PyCSLSemanticError
_ERR_UNPROTECTED_DECL = 'declared shared but has no protected_by mutex. All accesses are potential data races.'
_ERR_UNPROTECTED_WRITE = "Unprotected %s shared variable '%s' (requires '%s')"
_TRUSTED_CONCURRENT_TYPES = {'queue.Queue', 'Queue', 'threading.Lock', 'Lock', 'threading.RLock', 'RLock', 'threading.Semaphore', 'Semaphore', 'threading.Event', 'Event', 'threading.Condition', 'Condition', 'threading.Barrier', 'Barrier'}
_TRUSTED_ATTRIBUTES = {'put', 'get', 'acquire', 'release', 'wait', 'set', 'notify', 'notify_all', 'is_set'}
""  # pycsl
@dataclass
class ConcurrencyWarning:
    kind: str
    message: str
    function: str = ''
    line: int = 0

class ConcurrencyChecker:
    'Walk the annotated AST and emit ConcurrencyWarning objects.'
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __init__(self, tree: ast.AST, *, strict_mode: bool=False, filename: str='<input>') -> None:
        self.tree = tree
        self.warnings: List[ConcurrencyWarning] = []
        self.strict_mode = bool(strict_mode)
        self.filename = filename
        self._shared_vars: Dict[str, Optional[str]] = {}
        self._lock_order: Optional[List[str]] = None
        self._thread_entries: Set[str] = set()

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns self._lock_order, self._shared_vars, self._thread_entries, self.warnings
    def check(self) -> List[ConcurrencyWarning]:
        return []

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns self.warnings
    def _check_function(self, func: ast.FunctionDef) -> None:
        pass

    #@ requires True
    #@ ensures True
    # (#34) HONEST FRAME. This declared `\nothing` while its only statement calls
    # `self._walk_stmt`, which declares `#@ assigns self.warnings` — and `warnings` IS a
    # label of this file's emitted record, so the under-claim was MODEL-VISIBLE: every
    # caller-side abstract `val` minted from this contract asserted that `warnings` is
    # unchanged across the call. Found twice independently: by putting the declared frame
    # on the concrete `let` (Why3: "this expression produces an unlisted write effect")
    # and by widening `check-trusted-frame-honesty.py`'s MODEL-VISIBLE predicate from
    # "`@mutable_state` class" to "the EMITTED record declares the field".
    #@ assigns self.warnings
    def _walk_body(self, stmts: list, held: int, func_name: str) -> None:
        for stmt in stmts:
            self._walk_stmt(stmt, held, func_name)

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns self.warnings
    def _walk_stmt(self, node: ast.AST, held: int, func_name: str) -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns self.warnings
    def _warn_if_unprotected(self, var: str, held: int, func_name: str, line: int, write: bool) -> None:
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def summary(self) -> str:
        return ""


