"""Mirror of `src/pycsl/frontend/desugar.py`.

Generated by `bin/self-annotate-stub-gen.py`, then the two PURE functions were CONVERTED
to verbatim body ports (the `exec_splice.py` precedent: `_is_constant_exec` and
`_contains_exec` are body-faithful there, only the NodeTransformer visit method is a stub).
`_ChainDesugarer.visit_Compare` stays `\trusted` for the same reason `_ExecSplicer.
visit_Expr` does: it CONSTRUCTS `pure_ast` nodes and rewrites the tree in place, and the
mirror's value model carries no constructor for an arbitrary AST node.
"""
from __future__ import annotations
from frontend import pure_ast as ast
_REPEATABLE_CALLS = ('len', 'ord', 'abs', 'chr')
_NON_REPEATABLE = (ast.Await, ast.NamedExpr, ast.Yield, ast.YieldFrom, ast.ListComp, ast.SetComp, ast.DictComp, ast.GeneratorExp)
#@ requires True
#@ ensures True
#@ assigns \nothing
def _chain_operand_repeatable(node: object) -> bool:
    """Is `node` safe to EVALUATE TWICE, as the chain expansion does?"""
    for sub in ast.walk(node):
        if isinstance(sub, _NON_REPEATABLE):
            return False
        if isinstance(sub, ast.Call):
            if not (isinstance(getattr(sub, "func", None), ast.Name)
                    and sub.func.id in _REPEATABLE_CALLS
                    and not getattr(sub, "keywords", [])):
                return False
    return True

""  # pycsl
class _ChainDesugarer(ast.NodeTransformer):
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns self._n
    def visit_Compare(self, node):
        pass


#@ requires True
#@ ensures True
#@ raises PyCSLParseError when True
#@ assigns \nothing
def reject_unmodelled(tree: ast.AST) -> None:
    """Refuse the shapes Module 5 would SILENTLY DROP and that have no sound rewrite."""
    for node in ast.walk(tree):
        if isinstance(node, (ast.For, ast.While)) and node.orelse:
            raise PyCSLParseError(
                "`for ... else` / `while ... else` is not modelled: the `else` clause runs "
                "exactly when the loop finished without `break`, and the IR emitter reads "
                "only the loop body, so the clause would be silently DROPPED from the "
                "model. Rewrite it with an explicit flag.")
        if isinstance(node, ast.Slice) and node.step is not None:
            raise PyCSLParseError(
                "an EXTENDED slice `x[lo:hi:step]` is not modelled: the lowering is "
                "`Array.sub x lo (hi - lo)`, which ignores the step entirely, so the "
                "model would carry a DIFFERENT sequence — different length and different "
                "elements — from the one Python builds. Use an explicit strided loop.")



#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def normalize_stores(tree: ast.AST) -> None:
    """Rewrite the two ASSIGNMENT shapes Module 5 drops, in every statement list.

    `\trusted`, and the reason is the same one that made #32 RE-TRUST
    `pure_ast.copy_location`: the live body reads `getattr(node, field, None)` with `field`
    a LOOP VARIABLE — a DYNAMIC attribute name, which has no lowering, so a converted port
    would model the whole rewrite as a constant and be HOLLOW. It also CONSTRUCTS
    `ast.Assign` / `ast.Name` nodes, which the mirror's value model carries no constructor
    for."""
    pass


#@ requires True
#@ ensures True
#@ assigns \nothing
def desugar_chained_comparisons(tree: ast.AST) -> ast.AST:
    """Rewrite every multi-operator `Compare` into the `and`-chain Python means by it.
    No-op (byte-identical emission) for any file that contains no chained comparison."""
    return _ChainDesugarer().visit(tree)
