"""Mirror of `src/pycsl/frontend/desugar_compare.py`.

Generated by `bin/self-annotate-stub-gen.py`, then the two PURE functions were CONVERTED
to verbatim body ports (the `exec_splice.py` precedent: `_is_constant_exec` and
`_contains_exec` are body-faithful there, only the NodeTransformer visit method is a stub).
`_ChainDesugarer.visit_Compare` stays `\trusted` for the same reason `_ExecSplicer.
visit_Expr` does: it CONSTRUCTS `pure_ast` nodes and rewrites the tree in place, and the
mirror's value model carries no constructor for an arbitrary AST node.
"""
from __future__ import annotations
from frontend import pure_ast as ast
_REPEATABLE_CALLS = ('len', 'ord', 'abs', 'chr')
_NON_REPEATABLE = (ast.Await, ast.NamedExpr, ast.Yield, ast.YieldFrom, ast.ListComp, ast.SetComp, ast.DictComp, ast.GeneratorExp)
#@ requires True
#@ ensures True
#@ assigns \nothing
def _chain_operand_repeatable(node: object) -> bool:
    """Is `node` safe to EVALUATE TWICE, as the chain expansion does?"""
    for sub in ast.walk(node):
        if isinstance(sub, _NON_REPEATABLE):
            return False
        if isinstance(sub, ast.Call):
            if not (isinstance(getattr(sub, "func", None), ast.Name)
                    and sub.func.id in _REPEATABLE_CALLS
                    and not getattr(sub, "keywords", [])):
                return False
    return True

""  # pycsl
class _ChainDesugarer(ast.NodeTransformer):
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns self._n
    def visit_Compare(self, node):
        pass


#@ requires True
#@ ensures True
#@ assigns \nothing
def desugar_chained_comparisons(tree: ast.AST) -> ast.AST:
    """Rewrite every multi-operator `Compare` into the `and`-chain Python means by it.
    No-op (byte-identical emission) for any file that contains no chained comparison."""
    return _ChainDesugarer().visit(tree)
