"""Mirror of `src/pycsl/exec_splice.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from frontend import pure_ast as ast
from errors import PyCSLParseError
_WHITELIST = (ast.Assign, ast.AnnAssign, ast.AugAssign, ast.Expr)
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _is_constant_exec(call: object) -> bool:
    return False

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _contains_exec(node: object) -> bool:
    return False

""  # pycsl
class _ExecSplicer(ast.NodeTransformer):
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def visit_Expr(self, node):
        pass


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def splice_constant_exec(tree: ast.AST) -> ast.AST:
    return None

