"""Mirror of `src/pycsl/exec_splice.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from frontend import pure_ast as ast
from errors import PyCSLParseError
_WHITELIST = (ast.Assign, ast.AnnAssign, ast.AugAssign, ast.Expr)
#@ requires True
#@ ensures True
#@ assigns \nothing
def _is_constant_exec(call: object) -> bool:
    return (isinstance(call, ast.Call)
            and isinstance(getattr(call, "func", None), ast.Name)
            and call.func.id == "exec"
            and len(getattr(call, "args", [])) == 1
            and isinstance(call.args[0], ast.Constant)
            and isinstance(call.args[0].value, str))

#@ requires True
#@ ensures True
#@ assigns \nothing
def _contains_exec(node: object) -> bool:
    for sub in ast.walk(node):
        if isinstance(sub, ast.Call) and isinstance(getattr(sub, "func", None), ast.Name) \
                and sub.func.id == "exec":
            return True
    return False

""  # pycsl
class _ExecSplicer(ast.NodeTransformer):
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def visit_Expr(self, node):
        pass


#@ requires True
#@ ensures True
#@ assigns \nothing
def splice_constant_exec(tree: ast.AST) -> ast.AST:
    """Replace every constant-`exec` expression-statement with its parsed straight-line body.
    No-op (byte-identical emission) for any file that contains no constant `exec`."""
    return _ExecSplicer().visit(tree)

