"""Mirror of `src/pycsl/import_classifier.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
from frontend import pure_ast as ast
import os
from pathlib import Path
from typing import Dict, List, Set, Tuple
from errors import PyCSLSemanticError
TRUSTED_STUB = 'TRUSTED_STUB'
UNVERIFIED = 'UNVERIFIED'
UNRESOLVED = 'UNRESOLVED'
DEFAULT_DENY_LIST: frozenset = frozenset({'ctypes', 'ctypes.util', 'cffi', 'numpy.ctypeslib', 'cython'})
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _stub_set(stub_dir: Path) -> int:
    return set()

#@ requires True
#@ ensures True
#@ assigns \nothing
def classify(module_name: str, stubs: Set[str],
             deny_list: frozenset = DEFAULT_DENY_LIST) -> str:
    """Classify a single module name."""
    top = module_name.split(".", 1)[0]
    if module_name in deny_list or top in deny_list:
        return UNVERIFIED
    if module_name in stubs or top in stubs:
        return TRUSTED_STUB
    return UNRESOLVED

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def collect_imports(tree: ast.AST) -> List[int]:
    return []

#@ requires True
#@ ensures True
#@ assigns \nothing
def any_function_trusted(tree: ast.AST) -> bool:
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            if getattr(node, "csl_trusted", False):
                return True
    return False

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def check_imports(tree: ast.AST, *, stub_dir: Path, allow_unverified: bool=False, filename: str='<input>', deny_list: frozenset=DEFAULT_DENY_LIST) -> List[int]:
    return []

