"""Mirror of `src/pycsl/ir_inline.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
import copy
from typing import Any, Dict, List, Optional, Set, Tuple
from errors import PyCSLSemanticError
_MAX_INLINE_DEPTH = 16
#@ requires True
#@ ensures True
#@ assigns \nothing
def _walk_dicts(obj: Any):
    """Yield every dict node in an IR tree (depth-first)."""
    if isinstance(obj, dict):
        yield obj
        for v in obj.values():
            yield from _walk_dicts(v)
    elif isinstance(obj, list):
        for x in obj:
            yield from _walk_dicts(x)

#@ requires True
#@ ensures True
#@ assigns \nothing
def _touches_global(obj: Any, globals_set: int) -> bool:
    for node in _walk_dicts(obj):
        t = node.get("type") or node.get("stmt")
        if t == "Attribute":
            o = node.get("object")
            if (isinstance(o, dict) and o.get("type") == "Var"
                    and o.get("name") in globals_set):
                return True
        elif t in ("FieldGet", "FieldAssign", "FieldAugAssign"):
            if node.get("object") in globals_set:
                return True
    return False

#@ requires True
#@ ensures True
#@ assigns \nothing
def _method_key(cls: str, method: str) -> str:
    """The function-IR name for class `cls`'s method `method` (Module 5 mangling)."""
    return f"{cls.lower()}__{method}"

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _global_call_target(call: int, globals_set: int, g_class: int) -> Optional[str]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _method_edges(func: int, names: int, self_cls: str, globals_set: int, g_class: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _recursive_methods(funcs: List[int], globals_set: int, g_class: int) -> int:
    return set()

#@ requires True
#@ ensures True
#@ assigns \nothing
def _assigned_locals(stmts: Any) -> Set[str]:
    """Local names a method body binds (Assign/AugAssign/For targets) — freshened on
    inlining so they don't collide with (or capture) the caller's locals."""
    out: Set[str] = set()
    for node in _walk_dicts(stmts):
        s = node.get("stmt")
        if s in ("Assign", "AugAssign", "For") and isinstance(node.get("target"), str):
            out.add(node["target"])
    return out

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _substitute(node: Any, self_name: str, param_map: int, rename: int) -> Any:
    return None

""  # pycsl
class _Inliner:
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __init__(self, funcs, globals_set, g_class, recursive, no_inline=None):
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _fresh(self, base: str) -> str:
        return ""

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _expand(self, callee: str, recv: str, args: List[Any], result_var: Optional[str]) -> List[Any]:
        return []

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _hoist_calls_in_expr(self, node: Any, pre: List[Any]) -> Any:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def inline_stmts(self, stmts: List[Any]) -> List[Any]:
        return []


#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_no_aliasing(funcs: List[Dict[str, Any]], globals_set: Set[str]) -> None:
    for f in funcs:
        for node in _walk_dicts(f.get("body")):
            if (node.get("stmt") == "Assign" and isinstance(node.get("value"), dict)
                    and node["value"].get("type") == "Var"
                    and node["value"].get("name") in globals_set):
                raise PyCSLSemanticError(
                    f"cannot alias module global '{node['value']['name']}' into a local "
                    f"(inline.md Phase 3): a global is a single named object — call its "
                    f"methods or read its fields directly.")
            if node.get("type") == "Call":
                for a in node.get("args", []):
                    if (isinstance(a, dict) and a.get("type") == "Var"
                            and a.get("name") in globals_set):
                        raise PyCSLSemanticError(
                            f"cannot pass module global '{a['name']}' as an argument "
                            f"(inline.md Phase 3): would alias the global; operate on it "
                            f"via its own methods/fields.")

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _inline_calls(funcs: List[int], globals_set: int, g_class: int, rewrite_funcs: Optional[List[int]]=None) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def apply_inline_globals(ir_data: int) -> None:
    pass

