"""Mirror of `src/pycsl/ir_inline.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
import copy
from typing import Any, Dict, List, Optional, Set, Tuple
from errors import PyCSLSemanticError
_MAX_INLINE_DEPTH = 16
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _walk_dicts(obj: Any):
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _touches_global(obj: Any, globals_set: int) -> bool:
    return False

#@ requires True
#@ ensures True
#@ assigns \nothing
def _method_key(cls: str, method: str) -> str:
    """The function-IR name for class `cls`'s method `method` (Module 5 mangling)."""
    return f"{cls.lower()}__{method}"

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _global_call_target(call: int, globals_set: int, g_class: int) -> Optional[str]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _method_edges(func: int, names: int, self_cls: str, globals_set: int, g_class: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _recursive_methods(funcs: List[int], globals_set: int, g_class: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _assigned_locals(stmts: Any) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _substitute(node: Any, self_name: str, param_map: int, rename: int) -> Any:
    return None

""  # pycsl
class _Inliner:
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def __init__(self, funcs, globals_set, g_class, recursive, no_inline=None):
        pass

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _fresh(self, base: str) -> str:
        return ""

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _expand(self, callee: str, recv: str, args: List[Any], result_var: Optional[str]) -> List[Any]:
        return []

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def _hoist_calls_in_expr(self, node: Any, pre: List[Any]) -> Any:
        return None

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def inline_stmts(self, stmts: List[Any]) -> List[Any]:
        return []


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_no_aliasing(funcs: List[int], globals_set: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _inline_calls(funcs: List[int], globals_set: int, g_class: int, rewrite_funcs: Optional[List[int]]=None) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def apply_inline_globals(ir_data: int) -> None:
    pass

