"""Mirror of `src/pycsl/ir_resolve.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import copy
import json as _json
import os
from typing import Any, Dict, List, Optional, Set, Tuple
from frontend import pure_ast as _ast
from frontend.Module1_Ingestor import Module1_Ingestor
from frontend.Module2_Parser import Module2_Parser
from frontend.Module3_Weaver import Module3_Weaver
from frontend.Module5_IREmitter import Module5_IREmitter
from frontend.ir_inline import apply_inline_globals
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_calls(obj: Any) -> Set[str]:
    """Recursively collect function names from Call nodes in IR."""
    calls = set()
    if isinstance(obj, dict):
        if obj.get("type") == "Call":
            calls.add(obj["func"])
        for v in obj.values():
            calls |= _collect_calls(v)
    elif isinstance(obj, list):
        for item in obj:
            calls |= _collect_calls(item)
    return calls

#@ requires True
#@ ensures True
#@ assigns obj
def _rewrite_ir_calls(obj: Any, old_name: str, new_name: str) -> None:
    """Recursively rewrite Call nodes: func old_name → new_name."""
    if isinstance(obj, dict):
        if obj.get("type") == "Call" and obj.get("func") == old_name:
            obj["func"] = new_name
        for v in obj.values():
            _rewrite_ir_calls(v, old_name, new_name)
    elif isinstance(obj, list):
        for item in obj:
            _rewrite_ir_calls(item, old_name, new_name)

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _resolve_module_path(module_dotted: str, level: int, main_file: str) -> Optional[str]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _get_module_exports(filepath: str) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _process_dependency(filepath: str, needed_names: int, cache: int, deep: bool=False, processing_set: int=None) -> List[int]:
    return []

_DIR_CLASS_INV_AXIOMS = frozenset({'UnixFs.Dir.empty_disk_slots_dead', 'UnixFs.Dir.block5_decode_frame'})
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _strip_dir_scan_proofs(func: int) -> int:
    return {}

#@ requires True
#@ ensures True
#@ assigns \nothing
def _contract_referenced_var_names(dep_funcs: List[Dict[str, Any]]) -> Set[str]:
    """Collect every Var/object NAME referenced inside the contracts of the
    injected stubs — including the object of an `Attribute`/`FieldGet`
    (`_filesystem.disk` → `_filesystem`). Used to scope module-global
    propagation to globals the injected contracts actually touch (gap-9)."""
    referenced: Set[str] = set()

    def _walk(node: Any) -> None:
        if isinstance(node, dict):
            t = node.get("type")
            if t == "Var" and isinstance(node.get("name"), str):
                referenced.add(node["name"])
            obj = node.get("object")
            if isinstance(obj, str):
                referenced.add(obj)
            for v in node.values():
                _walk(v)
        elif isinstance(node, (list, tuple)):
            for v in node:
                _walk(v)

    for func in dep_funcs:
        contracts = func.get("contracts", {}) or {}
        _walk(contracts.get("requires", []))
        _walk(contracts.get("ensures", []))
        _walk(contracts.get("assigns", []))
    return referenced

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _find_record_type_from_dep_imports(rec_name: str, dep_file: str, cache: int, deep: bool, processing_set: int) -> int:
    return {}

#@ requires True
#@ ensures True
#@ assigns \nothing
def _contract_referenced_names(dep_funcs: List[Dict[str, Any]]) -> Set[str]:
    """Collect every callee name applied inside the contracts (`requires`/`ensures`)
    of the injected dependency stubs. Used by 11-0632-spec-8 Part 1 to scope inductive
    propagation to predicate names the public contracts actually reference (so unrelated
    internal predicates do not cross the import boundary)."""
    referenced: Set[str] = set()

    def _walk(node: Any) -> None:
        if isinstance(node, dict):
            if node.get("type") == "Call" and isinstance(node.get("func"), str):
                referenced.add(node["func"])
            for v in node.values():
                _walk(v)
        elif isinstance(node, (list, tuple)):
            for v in node:
                _walk(v)

    for func in dep_funcs:
        contracts = func.get("contracts", {}) or {}
        _walk(contracts.get("requires", []))
        _walk(contracts.get("ensures", []))
    return referenced

#@ requires True
#@ ensures True
#@ assigns \nothing
def _contract_referenced_var_names(dep_funcs: List[Dict[str, Any]]) -> Set[str]:
    """Collect every bare-variable name read inside the contracts
    (`requires`/`ensures`/`assigns`) of the injected dependency stubs — both
    plain `Var` references and the `object` of an `Attribute` projection
    (`_filesystem.disk` → `_filesystem`). Used by 11-1039-spec-10 to scope
    module-global propagation to ONLY the globals an injected public contract
    actually references (so unrelated dependency globals do not cross the import
    boundary, keeping the propagation byte-additive)."""
    referenced: Set[str] = set()

    def _walk(node: Any) -> None:
        if isinstance(node, dict):
            ntype = node.get("type")
            if ntype == "Var" and isinstance(node.get("name"), str):
                referenced.add(node["name"])
            elif ntype == "Attribute":
                obj = node.get("object")
                if isinstance(obj, dict) and obj.get("type") == "Var" \
                        and isinstance(obj.get("name"), str):
                    referenced.add(obj["name"])
            for v in node.values():
                _walk(v)
        elif isinstance(node, (list, tuple)):
            for v in node:
                _walk(v)

    for func in dep_funcs:
        contracts = func.get("contracts", {}) or {}
        _walk(contracts.get("requires", []))
        _walk(contracts.get("ensures", []))
        _walk(contracts.get("assigns", []))
    return referenced

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _inject_functions(dep_funcs: List[int], ir_data: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _resolve_direct_imports(direct_imports: List[Any], all_calls: int, main_file: str, ir_data: int, deep: bool, cache: int, processing_set: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _resolve_wildcard_imports(wildcard_imports: List[Any], all_calls: int, main_file: str, ir_data: int, deep: bool, cache: int, processing_set: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _resolve_module_imports(module_imports: List[Any], all_calls: int, main_file: str, ir_data: int, deep: bool, cache: int, processing_set: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _resolve_imported_classes(direct_imports: List[Any], main_file: str, ir_data: int, deep: bool, cache: int, processing_set: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _resolve_imported_base_classes(module_imports: List[Any], main_file: str, ir_data: int, deep: bool, cache: int, processing_set: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def apply_inheritance(ir_data: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def apply_composition(ir_data: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def resolve_imports(validated_ast: _ast.AST, main_file: str, ir_data: int, deep: bool=False, cache: int=None, processing_set: int=None) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def resolve(ir_data: int, validated_ast: _ast.AST, main_file: str, deep: bool=False) -> int:
    return set()

