"""Mirror of `src/pycsl/monomorphize.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import copy
import re
from typing import Any, Dict, List, Optional, Set, Tuple
from errors import PyCSLSemanticError
from frontend import pure_ast as _ast
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def apply_monomorphization(ir_data: int, validated_ast: Any=None) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_generic_decls(ir_data: int) -> int:
    return {}

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_gt3_schema_only(generics: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_instantiations(ir_data: int, generics: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _find_subscript_calls(body: List[int], generic_names: int) -> List[int]:
    return []

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _scan_node_for_subscript_calls(node: Any, generic_names: int) -> List[int]:
    return []

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _type_str(node: Any) -> Optional[str]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _sanitize_type_name(name: str) -> Optional[str]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _match_generic_annotation(type_str: Any, generic_names: int) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_instantiations_ast(tree: Any, generics: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _extract_ast_subscript(node: Any, generic_names: int) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_gt4_polymorphic_recursion(ir_data: int, generics: int, instantiations: int, validated_ast: Any=None) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_bounds(generics: int, instantiations: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _emit_specializations(ir_data: int, generics: int, instantiations: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _mangled_name(generic_name: str, concrete_type: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _specialize_decl(decl: int, tvar: str, concrete: str, new_name: str) -> int:
    return {}

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _specialize_function(func: int, tvar: str, concrete: str, new_class_name: str, new_self_type: Optional[str]=None) -> int:
    return {}

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _subst_type_in_ir(node: Any, tvar: str, concrete: str) -> Any:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_call_sites(ir_data: int, rename_map: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_subscript_calls_in_stmt(stmt: Any, rename_map: int) -> Any:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_subscript_to_name(node: Any, rename_map: int) -> Any:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_annotations(ir_data: int, rename_map: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_annotation_str(type_str: Any, rename_map: int) -> Any:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _record_classification(ir_data: int, generics: int, instantiations: int) -> None:
    pass

