"""Mirror of `src/pycsl/monomorphize.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import copy
import re
from typing import Any, Dict, List, Optional, Set, Tuple
from errors import PyCSLSemanticError
from frontend import pure_ast as _ast
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def apply_monomorphization(ir_data: int, validated_ast: Any=None) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_generic_decls(ir_data: int) -> int:
    return {}

#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_gt3_schema_only(generics: Dict[str, Dict[str, Any]]) -> None:
    for gname, info in generics.items():
        for tp in info["type_params"]:
            kind = tp.get("kind", "TypeVar")
            if kind != "TypeVar":
                raise PyCSLSemanticError(
                    f"monomorphization: generic {gname!r} declares a {kind} "
                    f"({tp.get('name')!r}) — GT3: ParamSpec/TypeVarTuple are "
                    f"schema-only and not interpreted (typing-global-overview.md "
                    f"§5 GT3). Use a plain TypeVar `T`.",
                    stage="monomorphize", code="PYCSL-TY3-GT3",
                )

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_instantiations(ir_data: int, generics: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _find_subscript_calls(body: List[int], generic_names: int) -> List[int]:
    return []

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _scan_node_for_subscript_calls(node: Any, generic_names: int) -> List[int]:
    return []

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _type_str(node: Any) -> Optional[str]:
    return None

#@ requires True
#@ ensures True
#@ assigns \nothing
def _sanitize_type_name(name: str) -> Optional[str]:
    """Normalize a concrete type name to one of the PyCSL primitive tags or a
    user class name. Returns None for Any/unrecognized."""
    if not name:
        return None
    if name == "Any":
        return "Any"  # caught by GT1 in the caller
    # PyCSL primitive tags.
    if name in ("int", "bool", "str", "bytes", "float", "list", "dict", "set"):
        # bool is modeled as int in PyCSL; keep the source name for clarity,
        # the substitution maps both to WhyML int.
        return name
    return name

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _match_generic_annotation(type_str: Any, generic_names: int) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _collect_instantiations_ast(tree: Any, generics: int) -> int:
    return set()

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _extract_ast_subscript(node: Any, generic_names: int) -> int:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_gt4_polymorphic_recursion(ir_data: int, generics: int, instantiations: int, validated_ast: Any=None) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _check_bounds(generics: int, instantiations: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _emit_specializations(ir_data: int, generics: int, instantiations: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _mangled_name(generic_name: str, concrete_type: str) -> str:
    return ""

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _specialize_decl(decl: int, tvar: str, concrete: str, new_name: str) -> int:
    return {}

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _specialize_function(func: int, tvar: str, concrete: str, new_class_name: str, new_self_type: Optional[str]=None) -> int:
    return {}

#@ requires wf_ir_deep(node)
#@ requires in_emitted_fragment(node)
#@ ensures size(\result) > 0
#@ ensures wf_ir_deep(\result)
#@ ensures in_emitted_fragment(\result)
#@ assigns \nothing
def _subst_type_in_ir(node: Any, tvar: str, concrete: str) -> Any:
    if isinstance(node, dict):
        new = {}
        for k, v in node.items():
            if k == "name" and v == tvar and node.get("type") == "Var":
                new[k] = concrete
            elif k == "return_annotation" and v == tvar:
                new[k] = concrete
            else:
                new[k] = _subst_type_in_ir(v, tvar, concrete)
        # Also handle field-type strings and annotation strings.
        if "type" in new and new["type"] == tvar:
            new["type"] = concrete
        return new
    if isinstance(node, list):
        return [_subst_type_in_ir(item, tvar, concrete) for item in node]
    return node

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_call_sites(ir_data: int, rename_map: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_subscript_calls_in_stmt(stmt: Any, rename_map: int) -> Any:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_subscript_to_name(node: Any, rename_map: int) -> Any:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_annotations(ir_data: int, rename_map: int) -> None:
    pass

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _rewrite_annotation_str(type_str: Any, rename_map: int) -> Any:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _record_classification(ir_data: int, generics: int, instantiations: int) -> None:
    pass

