/-
  WhyML.lean — WhyML Subset AST
  Defines the 13-constructor WhyML subset generated by Module 6.
  "Module 6" = `src/pycsl/Module6_WhyMLTranspiler.py` (facade) +
  `src/pycsl/module6_whyml/` (10 emission mixins, post-refactor).

  Design: runtime expression positions use `Expr`; spec positions
  (invariants, variants, assertions, ghost values) use `ContractExpr`.
  This mirrors Module 6's output structure and makes `gen` (StmtGen)
  a near-identity function.
-/
import PyCSL.AST

-- Exception name type: four flavours Module6 can generate
inductive WhyMLExc where
  | excReturn               -- SReturn e  → WSeq (WAssign "\result" e) (WRaise excReturn)
  | excBreak                -- SBreak     → WRaise excBreak
  | excContinue             -- SContinue  → WRaise excContinue
  | excNamed (name : Ident) -- SRaise exc → WRaise (excNamed exc)

-- WhyML statement AST — exactly the constructs Module6 can emit.
-- Runtime expressions (evalBool / evalExpr) keep type Expr.
-- Spec expressions (evalC / evalV) keep type ContractExpr = GhostExpr.
inductive WhyMLStmt where
  | wSkip
  -- runtime assignments
  | wAssign    (x : Ident)   (e : Expr)
  | wAugAssign (x : Ident)   (op : Binop)   (e : Expr)
  | wArraySet  (arr : Ident) (i : Expr)     (v : Expr)
  -- control flow
  | wSeq       (w1 w2 : WhyMLStmt)
  | wIf        (cond : Expr) (wThen wElse : WhyMLStmt)
  -- invs/vars are lists to mirror Module 6's one-line-per-source-invariant
  -- emission (parallels Rocq WWhile, extended 2026-05-28).
  | wWhile     (invs : List ContractExpr) (vars : List ContractExpr)
               (cond : Expr) (body : WhyMLStmt)
  -- exception-encoded control flow
  | wRaise     (exc : WhyMLExc)
  | wTryCatch  (body : WhyMLStmt) (exc : Ident) (handler : WhyMLStmt)
  -- ghost statements — GhostExpr = ContractExpr
  | wGhostDecl   (x : Ident) (t : GhostType) (e : GhostExpr)
  | wGhostAssign (x : Ident) (t : GhostType) (op : AugOp) (e : GhostExpr)
  | wLabel     (L : Ident)
  -- assertion — spec-level condition
  | wAssert    (cond : ContractExpr) (msg : String)

/-- Right-leaning conjunction of a list of contract expressions —
    collapses multi-invariant whiles to a single conjoined invariant
    for WP rules. -/
def cConj : List ContractExpr → ContractExpr
  | []        => .boolLit true
  | [c]       => c
  | c :: rest => .and c (cConj rest)

/-- First element (with default) for variant lists. -/
def cFirst : List ContractExpr → ContractExpr
  | []     => .int 0
  | c :: _ => c
