"""Mirror of `src/pycsl/struct_format.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import re
from dataclasses import dataclass
from typing import List, Optional, Tuple
_CHAR_TO_TYPE = {'x': None, 'b': 'int', 'B': 'int', 'h': 'int', 'H': 'int', 'i': 'int', 'I': 'int', 'l': 'int', 'L': 'int', 'q': 'int', 'Q': 'int', 'f': 'int', 'd': 'int', '?': 'int', 's': 'array int', 'c': 'array int', 'p': 'array int'}
_VALID_PREFIXES = {'@', '=', '<', '>', '!'}
""  # pycsl
@dataclass(frozen=True)
class StructFormat:
    "Parsed `struct` format-string descriptor.\n\n    Attributes\n    ----------\n    raw : str\n        Original format string (no prefix-strip).\n    prefix : str\n        Byte-order prefix or '' if absent.\n    slots : list[str]\n        WhyML type per packed/unpacked slot, in order. Pad bytes are\n        excluded.  E.g. for `'>IHHHHHII10Ixx'` this is\n        `['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int',\n         'int', 'int', 'int', 'int', 'int', 'int', 'int', 'int',\n         'int', 'int']` (18 ints).\n    "
    raw: str
    prefix: str
    slots: int
    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    @property
    def arity(self) -> int:
        return 0

    #@ \trusted reviewer: pycsl-self-annotate
    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def slot_id(self) -> str:
        return ""


#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def _short_type(t: str) -> str:
    return ""

_TOKEN_RE = re.compile('(\\d*)([A-Za-z?])')
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def parse_format(fmt: str) -> Optional[StructFormat]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def calcsize(fmt: str) -> int:
    return None

