"""Mirror of `src/pycsl/struct_format.py`. Trusted stub.

Generated by `bin/self-annotate-stub-gen.py`. Each function is
annotated `#@ \trusted reviewer: pycsl-self-annotate`; bodies
are stubs. The interface (parameter types, return type) matches
the source. The mirror-check gate enforces signature parity.
"""
from __future__ import annotations
import re
from dataclasses import dataclass
from typing import List, Optional, Tuple
_CHAR_TO_TYPE = {'x': None, 'b': 'int', 'B': 'int', 'h': 'int', 'H': 'int', 'i': 'int', 'I': 'int', 'l': 'int', 'L': 'int', 'q': 'int', 'Q': 'int', 'f': 'int', 'd': 'int', '?': 'int', 's': 'array int', 'c': 'array int', 'p': 'array int'}
_VALID_PREFIXES = {'@', '=', '<', '>', '!'}
""  # pycsl
@dataclass(frozen=True)
class StructFormat:
    "Parsed `struct` format-string descriptor.\n\n    Attributes\n    ----------\n    raw : str\n        Original format string (no prefix-strip).\n    prefix : str\n        Byte-order prefix or '' if absent.\n    slots : list[str]\n        WhyML type per packed/unpacked slot, in order. Pad bytes are\n        excluded.  E.g. for `'>IHHHHHII10Ixx'` this is\n        `['int', 'int', 'int', 'int', 'int', 'int', 'int', 'int',\n         'int', 'int', 'int', 'int', 'int', 'int', 'int', 'int',\n         'int', 'int']` (18 ints).\n    "
    raw: str
    prefix: str
    slots: List[str]
    # CONVERTED (relaunch #16), the first `@property` in the mirror to become a real
    # definition. Verbatim body port of the LIVE `arity`; `len(self.slots)` over the
    # `array int` slot field is `Array.length self.slots`.
    #@ requires True
    #@ ensures True
    #@ ensures \result >= 0
    #@ assigns \nothing
    @property
    def arity(self) -> int:
        return len(self.slots)

    #@ requires True
    #@ ensures True
    #@ assigns \nothing
    def slot_id(self) -> str:
        if not self.slots:
            return "empty"
        out: List[str] = []
        run_type = self.slots[0]
        run_count = 1
        for t in self.slots[1:]:
            if t == run_type:
                run_count += 1
            else:
                out.append(_short_type(run_type) + str(run_count))
                run_type, run_count = t, 1
        out.append(_short_type(run_type) + str(run_count))
        return "".join(out)
#@ requires True
#@ ensures True
#@ assigns \nothing
def _short_type(t: str) -> str:
    if t == "int":
        return "i"
    if t == "array int":
        return "a"
    return "x"

_TOKEN_RE = re.compile('(\\d*)([A-Za-z?])')
#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def parse_format(fmt: str) -> Optional[StructFormat]:
    return None

#@ \trusted reviewer: pycsl-self-annotate
#@ requires True
#@ ensures True
#@ assigns \nothing
def calcsize(fmt: str) -> int:
    return None

