"""
agent-rocq-proof-writer.py — Completes Rocq (Coq) proof obligations.

Receives a .v file generated by Why3 (proof skeleton with empty Proof./Qed. block)
and uses an LLM to fill in proof tactics. Validates the completed proof with coqc.

CLI args:
  --in     path to input .v file (Why3-generated skeleton)
  --out    path to output .v file (completed proof)
  --mlw    optional path to .mlw source for context
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from llm_client import llm_generate, log

AGENT_NAME = "agent-rocq-proof-writer"

MAX_RETRIES = 3

WHY3_COQ_LIB_PATHS = [
    Path.home() / ".opam" / "default" / "lib" / "why3" / "coq",
    Path.home() / ".opam" / "default" / "lib" / "coq" / "user-contrib" / "Why3",
]


def _find_why3_coq_lib() -> str:
    """Find the Why3 Coq library path for coqc -R flag."""
    for p in WHY3_COQ_LIB_PATHS:
        if p.exists() and (p / "BuiltIn.vo").exists():
            return str(p)
    # Try dynamic resolution via opam
    try:
        result = subprocess.run(
            ["opam", "var", "why3:lib"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            coq_path = Path(result.stdout.strip()) / "coq"
            if coq_path.exists():
                return str(coq_path)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return str(WHY3_COQ_LIB_PATHS[0])


def _load_config(config_path: Path) -> dict:
    """Load agents-config.json."""
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def _load_skill(config: dict, script_dir: Path) -> str:
    """Load the rocq-prover skill content."""
    skill_path = config.get("skill-rocq-prover", "")
    if not skill_path:
        return ""
    p = Path(skill_path)
    if not p.is_absolute():
        p = script_dir / p
    if p.exists():
        return p.read_text(encoding="utf-8")
    return ""


def _retrieve_skill_chunks(
    index_path: Path, input_code: str, top_k: int, project_root: Path
) -> str | None:
    """Retrieve relevant skill chunks via RAG."""
    if not index_path.exists():
        return None
    try:
        skill2rag_path = str(project_root / "src")
        if skill2rag_path not in sys.path:
            sys.path.insert(0, skill2rag_path)
        from skill2rag.retriever import retrieve

        chunks = []
        seen_ids = set()
        queries = [
            "Rocq Coq proof tactics lia split generalize",
            "Why3 proof obligation Theorem Proof Qed",
            input_code[:600],
        ]
        for query in queries:
            for chunk in retrieve(query=query, index_path=str(index_path), top_k=top_k):
                if chunk.chunk_id not in seen_ids:
                    seen_ids.add(chunk.chunk_id)
                    chunks.append(chunk)
        if not chunks:
            return None
        return "\n\n---\n\n".join(c.text for c in chunks[:top_k * 2])
    except Exception:
        return None


def _build_prompt(skill_content: str, v_content: str, mlw_content: str | None) -> str:
    """Build the LLM prompt for proof completion."""
    parts = []
    if skill_content:
        parts.append(skill_content)

    parts.append("""
# TASK
You are completing a Rocq (Coq) proof obligation generated by Why3.

The .v file below has an empty proof block between `Proof.` and `Qed.`.
Fill in the proof tactics to complete the proof.

CRITICAL RULES:
1. Add `Require Import Lia.` after the Why3 imports (after the last `Require` line, before any Definition/Inductive).
2. Do NOT modify anything outside the `Proof. ... Qed.` block (except adding `Require Import Lia.`).
3. Try `lia` first — it solves most goals.
4. For conjunctions, use `split` then `lia` on subgoals.
5. Bring axioms into scope with `generalize AxiomName.` then `intros.` before `lia`.
6. For non-linear arithmetic, try `nia`.
7. If the goal is genuinely unprovable from the given axioms, use `Abort.` instead of `Qed.` and add a comment explaining why.

Output ONLY the complete .v file content between "```coq" and "```".
""")

    if mlw_content:
        parts.append(f"# WHYML SOURCE (for context)\n```whyml\n{mlw_content}\n```\n")

    parts.append(f"# PROOF OBLIGATION\n```coq\n{v_content}\n```")

    return "\n\n".join(parts)


def _build_retry_prompt(
    skill_content: str, v_content: str, error: str, attempt: int
) -> str:
    """Build retry prompt with error feedback."""
    return f"""{skill_content}

# TASK (retry {attempt}/{MAX_RETRIES})
The previous proof attempt did not compile. Here is the coqc error:

```
{error}
```

Please fix the proof. Remember:
- Add `Require Import Lia.` after the Why3 imports
- Use `lia` for linear integer arithmetic
- Use `generalize <AxiomName>. intros.` to bring axioms into scope
- For non-linear arithmetic, try `nia`
- If the goal is unprovable from the given axioms, use `Abort.` instead of `Qed.`

Here is the .v file to fix:

```coq
{v_content}
```

Output ONLY the complete .v file content between "```coq" and "```".
"""


def _extract_coq_code(response: str) -> str | None:
    """Extract Coq code from markdown fences."""
    match = re.search(r"```(?:coq|v)\s*\n(.*?)```", response, re.DOTALL)
    if match:
        return match.group(1).strip()
    # Fallback: if no fences, check if the response looks like Coq code
    if "Require" in response and ("Theorem" in response or "Lemma" in response):
        return response.strip()
    return None


def _validate_with_coqc(v_content: str, why3_coq_lib: str) -> tuple[bool, str]:
    """Validate a .v file by compiling with coqc. Returns (success, error_output)."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".v", delete=False, encoding="utf-8"
    ) as f:
        f.write(v_content)
        temp_path = f.name
    try:
        result = subprocess.run(
            ["coqc", "-R", why3_coq_lib, "Why3", temp_path],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            return True, ""
        return False, (result.stderr or result.stdout or "Unknown error")
    except subprocess.TimeoutExpired:
        return False, "coqc timed out after 60 seconds"
    except FileNotFoundError:
        return False, "coqc not found — ensure Coq is installed and on PATH"
    finally:
        try:
            os.unlink(temp_path)
            # Clean up .vo and .glob files
            for ext in [".vo", ".glob", ".vok", ".vos"]:
                p = temp_path.replace(".v", ext)
                if os.path.exists(p):
                    os.unlink(p)
        except OSError:
            pass


def _has_abort(content: str) -> bool:
    """Check if the proof uses Abort instead of Qed."""
    return bool(re.search(r'\bAbort\b', content))


def main():
    parser = argparse.ArgumentParser(description="Complete Rocq proof obligations")
    parser.add_argument("--in", dest="input_file", required=True,
                        help="Path to input .v file (Why3-generated skeleton)")
    parser.add_argument("--out", required=True,
                        help="Path to output .v file (completed proof)")
    parser.add_argument("--mlw", default=None,
                        help="Path to .mlw file for context")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent.parent.parent

    # Load config
    config_path = script_dir / "agents-config.json"
    if not config_path.exists():
        config_path = project_root / "config" / "agents-config.json"
    config = _load_config(config_path)

    model = config.get("model", "claude-sonnet-4.6")
    log_dir = str(project_root / "project")

    # Load skill (RAG or full file)
    rag_index = config.get("rag-index", "")
    rag_top_k = config.get("rag-top-k", 10)
    v_content = Path(args.input_file).read_text(encoding="utf-8")

    skill_content = None
    if rag_index:
        rag_path = Path(rag_index)
        if not rag_path.is_absolute():
            rag_path = project_root / rag_path
        skill_content = _retrieve_skill_chunks(rag_path, v_content, rag_top_k, project_root)

    if not skill_content:
        skill_content = _load_skill(config, project_root)

    # Load optional .mlw context
    mlw_content = None
    if args.mlw and Path(args.mlw).exists():
        mlw_content = Path(args.mlw).read_text(encoding="utf-8")

    # Find Why3 Coq library
    why3_coq_lib = _find_why3_coq_lib()
    log(log_dir, AGENT_NAME, f"Why3 Coq lib: {why3_coq_lib}\n")
    log(log_dir, AGENT_NAME, f"Input: {args.input_file}\n")

    # Build and send prompt
    prompt = _build_prompt(skill_content, v_content, mlw_content)
    system = (
        "You are an expert Rocq/Coq theorem prover. You complete proof obligations "
        "generated by Why3 for formally verified Python programs. You produce minimal, "
        "correct proof scripts."
    )

    best_attempt = v_content  # fallback: the original skeleton

    for attempt in range(1, MAX_RETRIES + 1):
        log(log_dir, AGENT_NAME, f"Attempt {attempt}/{MAX_RETRIES}\n")

        if attempt == 1:
            response = llm_generate(
                prompt=prompt, system=system, agent_id=AGENT_NAME, model=model
            )
        else:
            retry_prompt = _build_retry_prompt(
                skill_content, best_attempt, last_error, attempt
            )
            response = llm_generate(
                prompt=retry_prompt, system=system, agent_id=AGENT_NAME, model=model
            )

        coq_code = _extract_coq_code(response)
        if not coq_code:
            log(log_dir, AGENT_NAME, "Failed to extract Coq code from LLM response\n")
            last_error = "Could not extract Coq code from response"
            continue

        best_attempt = coq_code

        # Check for Abort (intentionally unprovable)
        if _has_abort(coq_code):
            log(log_dir, AGENT_NAME, "Proof uses Abort — goal may be unprovable\n")
            Path(args.out).parent.mkdir(parents=True, exist_ok=True)
            Path(args.out).write_text(coq_code, encoding="utf-8")
            print(f"Proof aborted (unprovable): {args.out}", file=sys.stderr)
            sys.exit(1)

        # Validate with coqc
        success, error = _validate_with_coqc(coq_code, why3_coq_lib)
        if success:
            log(log_dir, AGENT_NAME, f"Proof validated by coqc ✓\n")
            Path(args.out).parent.mkdir(parents=True, exist_ok=True)
            Path(args.out).write_text(coq_code, encoding="utf-8")
            print(f"Proof completed: {args.out}")
            sys.exit(0)

        log(log_dir, AGENT_NAME, f"coqc failed: {error}\n")
        last_error = error

    # All retries exhausted — write best attempt with Abort
    log(log_dir, AGENT_NAME, f"All {MAX_RETRIES} attempts failed\n")
    # Replace Qed with Abort in the best attempt
    if "Qed." in best_attempt and not _has_abort(best_attempt):
        best_attempt = best_attempt.replace("Qed.", "Abort. (* coqc validation failed *)")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(best_attempt, encoding="utf-8")
    print(f"Proof incomplete (all retries failed): {args.out}", file=sys.stderr)
    sys.exit(1)


if __name__ == "__main__":
    main()
