"""Auto-generated `pycsl-bridge.manifest.toml`.

Per pycsl-bridge-plan.md §2.5. The manifest pairs each Python qualname
with the rocq + lean theorems that contracted it, plus the
reconciliation status. CI re-runs the bridge and diffs the regenerated
manifest against the committed one to catch drift (`check_manifest`).

The file format is TOML, intentionally line-oriented and stable so the
diff is human-reviewable:

    # Auto-generated by pycsl-bridge. Do not edit by hand.
    schema_version = 1

    [[entry]]
    python  = "double"
    rocq    = ["double_value", "double_is_even"]
    lean    = ["double_value", "double_is_even"]
    status  = "reconciled"

Entries are sorted by `python` for diff stability.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

# Use tomli_w if available; otherwise hand-roll the small subset we need.
try:
    import tomli_w  # type: ignore[import-not-found]
    _HAVE_TOMLI_W = True
except ModuleNotFoundError:
    _HAVE_TOMLI_W = False

import tomllib

from ..reconciler import Reconciliation


SCHEMA_VERSION = 1


@dataclass(frozen=True)
class ManifestEntry:
    python: str
    rocq: tuple[str, ...]
    lean: tuple[str, ...]
    status: str


@dataclass(frozen=True)
class Manifest:
    entries: tuple[ManifestEntry, ...]
    schema_version: int = SCHEMA_VERSION

    @classmethod
    def from_reconciliation(cls, rec: Reconciliation) -> "Manifest":
        entries = []
        for qn, r in sorted(rec.results.items()):
            rocq_thms = tuple(r.rocq["theorems"]) if r.rocq else ()
            lean_thms = tuple(r.lean["theorems"]) if r.lean else ()
            entries.append(ManifestEntry(
                python=qn,
                rocq=rocq_thms,
                lean=lean_thms,
                status=r.status.value,
            ))
        return cls(entries=tuple(entries))

    def to_toml(self) -> str:
        """Render the manifest as TOML text.

        Uses tomli_w if installed; otherwise emits a small hand-rolled
        TOML subset. The hand-rolled path is intentionally simple — the
        manifest schema is small and stable, so this avoids a new
        dependency.
        """
        if _HAVE_TOMLI_W:
            data = {
                "schema_version": self.schema_version,
                "entry": [
                    {
                        "python": e.python,
                        "rocq": list(e.rocq),
                        "lean": list(e.lean),
                        "status": e.status,
                    }
                    for e in self.entries
                ],
            }
            return (
                "# Auto-generated by pycsl-bridge. Do not edit by hand.\n"
                + tomli_w.dumps(data)
            )

        # Hand-rolled fallback.
        lines = [
            "# Auto-generated by pycsl-bridge. Do not edit by hand.",
            f"schema_version = {self.schema_version}",
            "",
        ]
        for e in self.entries:
            lines.append("[[entry]]")
            lines.append(f'python  = "{e.python}"')
            lines.append(f"rocq    = {_toml_string_list(e.rocq)}")
            lines.append(f"lean    = {_toml_string_list(e.lean)}")
            lines.append(f'status  = "{e.status}"')
            lines.append("")
        return "\n".join(lines).rstrip("\n") + "\n"


def _toml_string_list(items: tuple[str, ...]) -> str:
    if not items:
        return "[]"
    inner = ", ".join(f'"{i}"' for i in items)
    return f"[{inner}]"


def write_manifest(rec: Reconciliation, path: str | Path) -> Path:
    """Write the manifest derived from `rec` to `path`. Returns Path."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(Manifest.from_reconciliation(rec).to_toml())
    return p


def check_manifest(rec: Reconciliation, path: str | Path) -> bool:
    """True iff the committed manifest at `path` matches the manifest
    that would be regenerated from `rec`.

    Use in CI: regenerate from current sources, diff against the
    committed file. Mismatch means a contributor forgot to re-run the
    bridge after editing a spec.
    """
    fresh = Manifest.from_reconciliation(rec).to_toml()
    on_disk = Path(path).read_text() if Path(path).exists() else ""
    return _normalize(fresh) == _normalize(on_disk)


def _normalize(s: str) -> str:
    """Strip trailing whitespace per line and trailing blank lines."""
    return "\n".join(line.rstrip() for line in s.splitlines()).rstrip() + "\n"


def read_manifest(path: str | Path) -> Manifest:
    """Load a committed manifest. For tests and for `--check` flows."""
    data = tomllib.loads(Path(path).read_text())
    entries = tuple(
        ManifestEntry(
            python=e["python"],
            rocq=tuple(e.get("rocq", ())),
            lean=tuple(e.get("lean", ())),
            status=e.get("status", ""),
        )
        for e in data.get("entry", [])
    )
    return Manifest(
        entries=entries,
        schema_version=int(data.get("schema_version", SCHEMA_VERSION)),
    )
