"""wf_ir_gen.py — generate the per-(shape,key) `wf_val` typing predicate for the
wall-plan-v2 concrete-map theory FROM `ir_schema.py` (the schema is code).

WALL-PLAN v2, Phase 1 deliverable 3 (generic-dict-str-any-2-plan.md §2 E4):
E4 discharges an unguarded read `is_PStr (get n K_op)` from `requires wf_ir node`
via a per-(shape,key) lemma; the `wf_val` table those lemmas instantiate must be
*derived from the schema*, not hand-written, so it cannot drift from the real IR.

This tool AST-parses `ir_schema.py`, collects every typed field of every
`ExprIR`/`StmtIR` node class, maps each field's Python annotation to the `pyval`
constructor it lowers to, aggregates by wire-key name, and emits the WhyML
`wf_val` predicate body over the interned `irkey` set.  A field name that carries
a single consistent shape across all node kinds is CONSTRAINED to that shape; a
name with heterogeneous shapes (e.g. `value`, scalar in `Number` but a node in
`Assign`) stays unconstrained (`true`) — fail-open, never a false typing claim.

Usage:  python3 wf_ir_gen.py [path/to/ir_schema.py]   # prints the predicate
Importable: `generate_wf_val(schema_path) -> str`, `field_shape_map(...) -> dict`.
"""
from __future__ import annotations

import ast
import os
from typing import Dict, List, Optional, Set

# The interned key set of the WhyML theory (preamble `_emit_pydict_theory`).
# Only these wire keys have an `irkey` constructor; others route through K_dyn.
INTERNED_KEYS: List[str] = [
    "type", "left", "right", "op", "z",
    "value", "target", "body", "orelse", "func", "name",
]

# pyval constructors (the theory's `type pyval = PInt | PStr | PBool | PNone | PList | PDict`).
_PSTR, _PINT, _PBOOL, _PLIST, _PDICT = "PStr", "PInt", "PBool", "PList", "PDict"


def _annotation_to_shape(ann: str) -> Optional[str]:
    """Map a Python field annotation string to the pyval constructor it lowers to,
    or None for 'unconstrained' (Any / heterogeneous / optional-scalar)."""
    a = ann.strip().strip('"').strip("'")
    if a in ("str",):
        return _PSTR
    if a in ("int",):
        return _PINT
    if a in ("bool",):
        return _PBOOL
    if a in ("ExprIR", "StmtIR", "IRNode", "ContractExprIR"):
        return _PDICT
    if a.startswith("List") or a.startswith("list"):
        return _PLIST
    # Optional[...] / Any / Dict / unknown -> unconstrained (fail-open).
    return None


def field_shape_map(schema_path: str) -> Dict[str, Optional[str]]:
    """Return {wire_key: pyval_constructor or None} aggregated over every node class.

    A key mapping to exactly one constructor across all its occurrences is
    constrained; any disagreement (or an unconstrained occurrence) -> None."""
    with open(schema_path, "r", encoding="utf-8") as fh:
        tree = ast.parse(fh.read(), filename=schema_path)

    node_bases = {"ExprIR", "StmtIR", "IRNode"}
    seen: Dict[str, Set[Optional[str]]] = {}

    for cls in tree.body:
        if not isinstance(cls, ast.ClassDef):
            continue
        base_names = {b.id for b in cls.bases if isinstance(b, ast.Name)}
        if not (base_names & node_bases):
            continue
        for stmt in cls.body:
            if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
                continue
            fname = stmt.target.id
            if fname == "kind":  # the discriminant field, not a wire payload key
                continue
            ann = ast.unparse(stmt.annotation) if hasattr(ast, "unparse") else ""
            seen.setdefault(fname, set()).add(_annotation_to_shape(ann))

    result: Dict[str, Optional[str]] = {}
    for fname, shapes in seen.items():
        # 'type' is the discriminant tag string on the wire -> always PStr.
        if fname == "type":
            result[fname] = _PSTR
        elif len(shapes) == 1 and None not in shapes:
            result[fname] = next(iter(shapes))
        else:
            result[fname] = None
    # 'type' is not a dataclass field (it becomes `kind`); pin it explicitly.
    result.setdefault("type", _PSTR)
    return result


def generate_wf_val(schema_path: Optional[str] = None) -> str:
    """Emit the WhyML `wf_val` predicate body over the interned key set, derived
    from the schema.  The output is a drop-in refinement of the representative
    `wf_val` in `_emit_pydict_theory` (same signature `wf_val (k: irkey) (v: pyval)`)."""
    if schema_path is None:
        schema_path = os.path.join(os.path.dirname(__file__), os.pardir, "ir_schema.py")
    smap = field_shape_map(schema_path)

    lines: List[str] = [
        "  (* GENERATED by module6_whyml/wf_ir_gen.py from ir_schema.py — do not hand-edit. *)",
        "  predicate wf_val (k: irkey) (v: pyval)",
        "  = match k with",
    ]
    for key in INTERNED_KEYS:
        ctor = smap.get(key)
        kk = "K_" + key
        if ctor is None:
            lines.append(f"    | {kk} -> true")
        else:
            lines.append(
                f"    | {kk} -> (match v with {ctor} _ -> true | _ -> false end)"
            )
    lines.append("    | K_dyn _ -> true")
    lines.append("    end")
    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    path = sys.argv[1] if len(sys.argv) > 1 else None
    print(generate_wf_val(path))
